proxmox/virtual_environment_vm.go

Closes #2
Release note for [CHANGELOG](https://github.com/danitso/terraform-provider-proxmox/blob/master/CHANGELOG.md):
```release-note
```

Fix SIGSEGV if cloned VM is in a different storage.

---

proxmox/virtual_environment_container_types.go

This closes #15
Release note for [CHANGELOG](https://github.com/bpg/terraform-provider-proxmox/blob/main/CHANGELOG.md):
```release-note
```

Fix JSON unmarshal error when deploying LCX container

---

.github/workflows/test.yml
proxmoxtf/version.go

Bump provider version to 0.5.1

---

example/resource_virtual_environment_vm.tf
proxmox/virtual_environment_vm_types.go
proxmoxtf/resource_virtual_environment_vm.go

Add support for "iothread" disk option for VM

---

proxmoxtf/resource_virtual_environment_vm.go

Fixed Typo 

---

proxmox/common_types.go
proxmox/virtual_environment_client.go
proxmox/virtual_environment_cluster_ipset.go
proxmox/virtual_environment_container.go
proxmox/virtual_environment_container_types.go
proxmox/virtual_environment_datastores.go
proxmox/virtual_environment_nodes.go
proxmox/virtual_environment_vm.go
proxmox/virtual_environment_vm_types.go
proxmoxtf/data_source_virtual_environment_nodes.go
proxmoxtf/resource_virtual_environment_container.go
proxmoxtf/resource_virtual_environment_file.go
proxmoxtf/resource_virtual_environment_pool.go
proxmoxtf/resource_virtual_environment_time.go
proxmoxtf/resource_virtual_environment_vm.go
proxmoxtf/utils.go

Closes https://github.com/bpg/terraform-provider-proxmox/issues/149
This fix errors reported by linter, currently running with defaults. 
There are much more useful checks that can be enabled via config, which will be done in followup stories.

fix: linter issues

---

docs/resources/virtual_environment_vm.md
example/resource_virtual_environment_vm.tf
proxmoxtf/resource_virtual_environment_vm.go

feat: add support for VM tags

---

proxmox/virtual_environment_vm.go

feat: Deletion of VM also purges all storages and configs

---

docs/resources/virtual_environment_container.md
example/resource_virtual_environment_container.tf
proxmoxtf/resource_virtual_environment_container.go

feat(lxc): Add option to customize RootFS size at LXC creation

---

.github/workflows/golangci-lint.yml

chore: fix linter config

---

.github/workflows/test.yml
README.md
docs/resources/virtual_environment_container.md
docs/resources/virtual_environment_vm.md

chore: set up code coverage

---

docs/Gemfile.lock

chore(deps): bump gem dependencies in /docs

---

.github/workflows/test.yml

chore: disable code coverage

---

proxmoxtf/resource_virtual_environment_vm.go

fix(vm): ignore ssd disk flag with virtio interface

---

Makefile

fix(build): trailing space in provider's version

---

docs/resources/virtual_environment_container.md
proxmoxtf/resource_virtual_environment_container.go
proxmoxtf/resource_virtual_environment_container_test.go

Add configuration option for specifying the container as nesting or not.
Closes #250

feat(lxc): Add option for nested container feature

---

proxmoxtf/utils.go
proxmoxtf/utils_test.go

frat(vm): Add custom CPU models support

---

proxmox/virtual_environment_vm_types.go
proxmoxtf/resource_virtual_environment_vm.go

fix(vm): Fix `file_format` setting for new empty disks

---

docs/index.md
docs/resources/virtual_environment_vm.md

Relates to #247
Relates to #265

chore(docs): Minor documentation Improvements

---

proxmox/virtual_environment_authentication.go
proxmox/virtual_environment_client.go

chore: additional logging in API client

---

.github/workflows/golangci-lint.yml
.github/workflows/publish.yml
.github/workflows/test.yml
README.md
go.mod
tools/go.mod

feat: Update to Go 1.19

---

proxmoxtf/resource_virtual_environment_vm.go
proxmoxtf/resource_virtual_environment_vm_test.go
proxmoxtf/utils.go

feat(vm): Add scsi_hardware field

---

.github/PULL_REQUEST_TEMPLATE.md
docs/resources/virtual_environment_vm.md

chore: add missing docs

---

.github/PULL_REQUEST_TEMPLATE.md
proxmox/virtual_environment_nodes.go

fix(core): Error when open SSH session on Windows

---

proxmoxtf/resource/container.go
proxmoxtf/resource/utils.go
proxmoxtf/resource/vm.go

fix(vm,lxc): Tags reordering on plan re-apply

---

proxmoxtf/resource/container.go
proxmoxtf/resource/vm.go

fix(vm,lxc): Add validation for non-empty tags

---

CONTRIBUTING.md
README.md
docs/index.md

chore(doc): project documentation update

---

docs/resources/virtual_environment_vm.md
example/resource_virtual_environment_file.tf
example/resource_virtual_environment_vm.tf
proxmox/nodes/tasks/tasks.go
proxmoxtf/resource/vm.go

feat(vm): add support for meta-data in cloud-init

---

proxmoxtf/resource/file.go

fix(file): add check for supported content types when uploading file to a storage

---

CONTRIBUTING.md
proxmoxtf/resource/container.go

fix(lxc): add support for 'nixos'

---

proxmox/cluster/cluster.go
proxmox/cluster/cluster_types.go
proxmoxtf/resource/vm.go

fix: search for vm in cluster resources before calling node api

---

docs/resources/virtual_environment_firewall_options.md

Small typo in firewall options docs, no additional context or related issues

fix(docs): minor firewall options page improvement

---

proxmoxtf/provider/provider.go
proxmoxtf/provider/schema.go

fix(provider): fix config environment variables handling caused "rpc error"

---

docs/resources/virtual_environment_cluster_firewall.md
docs/resources/virtual_environment_cluster_firewall_security_group.md
docs/resources/virtual_environment_container.md
docs/resources/virtual_environment_dns.md
docs/resources/virtual_environment_file.md
docs/resources/virtual_environment_group.md
docs/resources/virtual_environment_hosts.md
docs/resources/virtual_environment_pool.md
docs/resources/virtual_environment_role.md
docs/resources/virtual_environment_time.md
docs/resources/virtual_environment_user.md
docs/resources/virtual_environment_vm.md
proxmoxtf/resource/cluster/firewall/firewall.go
proxmoxtf/resource/cluster/firewall/security_group.go
proxmoxtf/resource/container.go
proxmoxtf/resource/dns.go
proxmoxtf/resource/file.go
proxmoxtf/resource/file_test.go
proxmoxtf/resource/group.go
proxmoxtf/resource/hosts.go
proxmoxtf/resource/pool.go
proxmoxtf/resource/role.go
proxmoxtf/resource/time.go
proxmoxtf/resource/user.go
proxmoxtf/resource/utils.go
proxmoxtf/resource/utils_test.go
proxmoxtf/resource/vm.go

feat: add import support for a lot of resources

---

proxmox/nodes/network_types.go

fix(node): fix error when listing network interfaces of a node

---

proxmoxtf/resource/firewall/rules.go

fix(firewall): ignore non-existent rules at read/delete

---

proxmoxtf/resource/container.go
proxmoxtf/resource/firewall/selector.go
proxmoxtf/resource/utils.go
proxmoxtf/resource/validator/vm.go
proxmoxtf/resource/vm.go

fix(firewall): add VM / container ID validation to firewall rules

---

docs/resources/virtual_environment_vm.md
example/resource_virtual_environment_network.tf
proxmoxtf/resource/utils.go
proxmoxtf/resource/vm.go

fix(vm): add `interface` argument to `cdrom` block

---

docs/resources/virtual_environment_vm.md
example/resource_virtual_environment_vm.tf
proxmox/nodes/vms/vms_types.go
proxmox/nodes/vms/vms_types_test.go
proxmoxtf/resource/vm.go

feat(vm): add support for disk `cache` option

---

proxmoxtf/resource/vm.go

Also fixes for startup order (not released yet).

fix(vm): cloned VM with `efi_disk` got re-created at re-apply

---

.all-contributorsrc
README.md

chore: add all-contributors to README.md

---

.all-contributorsrc
README.md

chore(doc): add existing contributors

---

.all-contributorsrc
README.md

chore(doc): cleanup readme

---

docs/resources/virtual_environment_vm.md
example/resource_virtual_environment_vm.tf
proxmox/nodes/vms/vms_types.go
proxmoxtf/resource/vm.go

```terraform
smbios {
family       = "family"
manufacturer = "manufacturer"
product      = "product"
serial       = "serial"
sku          = "sku"
version      = "version"
}
```
Closes #451 
Closes #353

feat(vm): add support for SMBIOS settings

---

docs/resources/virtual_environment_vm.md
example/resource_virtual_environment_vm.tf
proxmoxtf/resource/vm.go
proxmoxtf/resource/vm_test.go

feat(vm): support for non-default CloudInit interface and CloudInit storage change

---

docs/resources/virtual_environment_container.md
proxmoxtf/resource/container.go
proxmoxtf/resource/container_test.go

feat(lxc): add support for `keyctl` and `fuse` features

---

proxmoxtf/provider/provider.go

Relates OR Closes https://github.com/bpg/terraform-provider-proxmox/issues/544

fix(provider): panic crash in provider, interface conversion error

---

.github/workflows/release-please.yml

misc: Sign-off release-please commits

---

docs/resources/virtual_environment_file.md

chore(docs): update `proxmox_virtual_environment_file` documentation

---

.github/workflows/release-please.yml

misc: fix Sign-off release-please commits

---

.github/PULL_REQUEST_TEMPLATE.md

chore(docs): add "Proof of Work" section to the PR template

---

proxmox/nodes/tasks/tasks_types.go
proxmox/nodes/tasks/tasks_types_test.go

- added a specific test for parsing `UPID:pve-srv:0012D68C:8206F38C:65144CB7:qmcreate:501:root@pam:` that passes after the fix.
Closes #589

fix(tasks): fix UPID (task id) parsing error

---

.github/workflows/golangci-lint.yml
.github/workflows/test.yml
proxmox/api/client.go
proxmox/api/ticket_auth.go
proxmoxtf/resource/file.go

fix(api): set min TLS version 1.3, secure HTTP-only cookie

---

proxmoxtf/resource/file.go

misc: fix tls min version typo

---

docs/resources/virtual_environment_vm.md
example/resource_virtual_environment_vm.tf
proxmox/nodes/tasks/tasks.go
proxmox/nodes/tasks/tasks_types.go
proxmox/nodes/vms/vms.go
proxmoxtf/resource/validator/vm.go
proxmoxtf/resource/vm.go

Example template:
```hcl
resource "proxmox_virtual_environment_vm" "ubuntu_vm" {
name = "575-cloudinit-scsi"
node_name = var.virtual_environment_node_name
vm_id     = 575
machine   = "q35"
bios      = "ovmf"
agent {
enabled = true
}
efi_disk {
file_format  = "raw"
type         = "4m"
}
disk {
file_id      = "local:iso/jammy-server-cloudimg-amd64.img"
interface    = "virtio0"
iothread     = true
discard      = "on"
size         = 20
}
interface = "scsi0"
ip_config {
ipv4 {
address = "dhcp"
}
}
user_account {
username = "ubuntu"
password = "ubuntu"
keys     = [trimspace(data.local_file.ssh_public_key.content)]
}
vendor_data_file_id = proxmox_virtual_environment_file.cloud_config.id
}
network_device {
bridge = "vmbr0"
} …
```

fet(vm): allow `scsi` and `sata` interfaces for CloudInit Drive

---

README.md

misc: add sponsorship note

---

docs/resources/virtual_environment_container.md
proxmoxtf/resource/container.go
proxmoxtf/resource/container_test.go

feat(lxc): add support for the `start_on_boot` option

---

docs/resources/virtual_environment_vm.md
example/resource_virtual_environment_vm.tf
proxmoxtf/resource/vm.go

feat(vm): add option to enable multiqueue in network devices

---

fwprovider/tests/resource_container_test.go
fwprovider/tests/resource_linux_vlan_test.go
fwprovider/tests/test_support.go
proxmox/nodes/containers/containers.go
proxmoxtf/resource/container.go

Added specific acceptance tests that pass.

fix(lxc): cloned container does not start by default

---

proxmox/ssh/client.go

fix(provider): add informative error around ssh-agent 

---

fwprovider/datasource_hagroup.go
fwprovider/datasource_hagroups.go
fwprovider/datasource_haresource.go
fwprovider/datasource_haresources.go
fwprovider/datasource_version.go
fwprovider/resource_hagroup.go
fwprovider/resource_haresource.go
fwprovider/resource_linux_bridge.go
fwprovider/resource_linux_vlan.go
fwprovider/resource_options.go
proxmoxtf/test/utils.go
utils/io_test.go

https://github.com/bpg/terraform-provider-proxmox/pull/636 bumped golangci-lint version that now started tripping on old code, so this PR is to address the "new" linter findings.

chore: fix linter error

---

.github/PULL_REQUEST_TEMPLATE.md
README.md
docs/resources/virtual_environment_file.md

fix(doc): update README.md and `file` resource documentation

---

docs/resources/virtual_environment_vm.md

chore(docs): update VM ip address to mention the CIDR suffic requirement

---

docs/resources/virtual_environment_file.md
proxmoxtf/resource/validator/vm.go

This now matches with the folder used by proxmox for backups
Also update documentation to reflect the change.
see comment in #700 before merging.
Closes #700

feat(file): rename content type `backup` -> `dump` for backups

---

fwprovider/resource_options.go
proxmox/cluster/options_types.go
proxmox/nodes/vms/vms_types.go
proxmox/types/common_types.go

Following PVE API [breakage](https://git.proxmox.com/?p=qemu-server.git;a=blobdiff;f=PVE/QemuServer.pm;h=1b1ccf4d989ada27b5bbd0581aba177ea5da6fcc;hp=e4abc3868e10aadb7b57ccd34e93fedc3e396fd9;hb=7f8c808772979f274cdfac1dc7264771a3b7a7ae;hpb=87b0f305e7084c21d8298ba521bf0d3a0fba694e) in qemu-server 8.0.8
Before:
After:
Closes #727

fix(vm): type error when unmarshalling `GetResponseData.data.memory`

---

docs/index.md
docs/resources/virtual_environment_container.md

fix(docs): improve documentation for container feature flags

---

README.md

doc: add Elias Alvord as a sponsor

---

.github/workflows/release-please.yml
.release-please-manifest.json
release-please-config.json

fix(ci): fix release-please config after version bump (part2)

---

.github/workflows/release-please.yml
.release-please-manifest.json
release-please-config.json

chore(deps): revert bump google-github-actions/release-please-action from 3.7.13 to 4.0.0

---

.github/workflows/release-please.yml

ci: configure release-please to bump minor version on breaking changes

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/PULL_REQUEST_TEMPLATE.md
.markdownlint.json
CONTRIBUTING.md

fix(docs): update CONTRIBUTING.md and other project docs

---

.golangci.yml
.vscode/settings.json

chore: configure vscode's linter to use proper .golangci.yml file

---

docs/resources/virtual_environment_vm.md
proxmoxtf/resource/vm.go

feat(vm): support stopping (rather than shutting down) VMs on resource destroy

---

examples/provider/provider.tf

👋 New to this repo, and I just spotted this typo when I was going over the code.

fix(provider): typo in provider example

---

docs/resources/virtual_environment_vm.md

Documents the behavior described in #551
Relates #551

fix(docs): add clone/full parameter for vms

---

docs/resources/virtual_environment_vm.md
example/resource_virtual_environment_vm.tf
proxmoxtf/resource/vm.go

```hcl
...
cpu {
cores = 2
numa  = true
limit = 64
}
...
```
Closes #804

feat(vm): add `cpu.limit` attribute

---

example/resource_virtual_environment_vm.tf
proxmoxtf/resource/vm.go

Based on change in [example/resource_virtual_environment_vm.tf](https://github.com/bpg/terraform-provider-proxmox/compare/fix-apply-smbios-at-clone?expand=1#diff-f00dd09a85fd21ebbb80098e495f4f3b897ad23ee1c83378e3017b5aaa385014)
Template VM:
```hcl
...
smbios {
manufacturer = "Terraform"
product      = "Terraform Provider Proxmox"
version      = "0.0.1"
}
...
```
Cloned VM:
```
...
smbios {
serial = "my-custom-serial"
}
...
```
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra …

fix(vm): update `smbios` during clone

---

.github/PULL_REQUEST_TEMPLATE.md
README.md
howtos/README.md
howtos/setup-proxmox-for-make-example/README.md

How-to like that can potentially encourage people to run `make example` before creating PRs.

docs: improve make example docs and add proxmox setup how-to

---

.vscode/extensions.json
.vscode/launch.json
CONTRIBUTING.md
Makefile
fwprovider/tests/datasource_version_test.go
fwprovider/tests/resource_container_test.go
fwprovider/tests/resource_file_test.go
fwprovider/tests/resource_linux_vlan_test.go
howtos/README.md
howtos/setup-proxmox-for-tests/README.md
proxmox/ssh/client.go

chore(tests): Update acceptance tests to PVE 8.1, add docs

---

example/resource_virtual_environment_container.tf
proxmoxtf/resource/container.go

Closes https://github.com/bpg/terraform-provider-proxmox/issues/794

fix(lxc): add missing `onboot` param on container clone create

---

proxmoxtf/resource/container.go
proxmoxtf/resource/vm.go

While trying to setup both IPv4 and IPv6 addresses in a VM, a validation error prevents adding IPv6 DNS in Cloud-Init `initialization`:
> Error: expected initialization.0.dns.0.servers.1 to contain a valid IPv4 address, got: x:x:x:x:x:x
Proxmox seems to accept both there, I have yet to get IPv6 connectivity working though.
`make example` fails due to an SSH connection error with my setup, but I guess only IPv4 is tested anyway.
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra …

fix(vm,lxc): accept IPv6 in `initialization.dns.servers` attribute

---

proxmoxtf/resource/container.go
proxmoxtf/resource/vm.go

fix(vm,lxc): unexpected state drift when using `initialization.dns.servers`

---

proxmoxtf/resource/vm.go

The default value of "ignore" was missing from the disk discard parameter of the terraform module. This commit sets the default to "ignore" instead of the current "".
This fixes terraform incorrectly flagging that the state is different than what is currently running on the proxmox node when the discard option isn't defined under the disk object.
Below shows the behaviour prior to the fix being applied:
Below shows the behaviour after the fix has been applied:
- Please do not leave "+1" or other comments that do not add relevant new information …

fix(vm): Fixed missing default for disk discard

---

.markdownlintignore
.vscode/settings.json
fwprovider/provider.go
proxmoxtf/provider/provider.go

feat(provider): add DNS lookup fallback for node IP resolution

---

README.md

misc: Update README.md

---

docs/resources/virtual_environment_file.md

fix(doc): typos in `proxmox_virtual_environment_file` resource

---

proxmoxtf/provider/provider.go

If nodeName IP lookup is successful `err` is nil

fix(provider): check if err is nil

---

docs/resources/virtual_environment_container.md

Fix incorrect indentation in `proxmox_virtual_environment_container` documentation for `disk` block which caused the `size` parameter to render incorrectly.
Current documentation as of 11 January 2024 on https://registry.terraform.io/providers/bpg/proxmox/latest/docs/resources/virtual_environment_container:
> ![image](https://github.com/bpg/terraform-provider-proxmox/assets/1216926/ffe379d1-a45a-411e-86ef-aa32ef8a868f)
Fixed documentation as viewed with GitHub's markdown renderer:
> ![image](https://github.com/bpg/terraform-provider-proxmox/assets/1216926/2479fd24-13cc-4b25-a45a-74f6c832cce7)
- Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the …

fix(docs): fix indentation in `virtual_environment_container.md`

---

docs/resources/virtual_environment_container.md
example/resource_virtual_environment_container.tf
proxmoxtf/resource/container.go

feat(lxc): add container startup options

---

proxmoxtf/resource/vm.go

Apply & reapply a template with
```hcl
...
dns {}
...
}
```
```
Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following
symbols:
~ update in-place
Terraform will perform the following actions:
~ resource "proxmox_virtual_environment_vm" "ubuntu_vm" {
id                      = "1000"
name                    = "test"
tags                    = []
~ cpu {
+ architecture = "x86_64"
}
~ initialization {
+ dns {}
}
}
Plan: 0 to add, 1 to change, 0 to destroy.
proxmox_virtual_environment_vm.ubuntu_vm: Modifying... [id=1000]
proxmox_virtual_environment_vm.ubuntu_vm: Still modifying... [id=1000, 10s elapsed]
proxmox_virtual_environment_vm.ubuntu_vm: Still modifying... [id=1000, 20s elapsed] …
```

fix(vm): panic on empty `initialization.dns` block

---

docs/index.md
docs/resources/virtual_environment_file.md
fwprovider/provider.go
fwprovider/tests/test_support.go
proxmox/api/client.go
proxmoxtf/provider/provider.go
proxmoxtf/provider/provider_test.go
proxmoxtf/provider/schema.go
proxmoxtf/resource/file.go

Closes https://github.com/bpg/terraform-provider-proxmox/issues/930

feat: add min-tls option to provider config

---

.vscode/settings.json
Makefile
README.md

chore(docs): update README.md, add note about OpenTofu support

---

.github/workflows/golangci-lint.yml
.github/workflows/link-check.yml
.github/workflows/metrics.yml
.github/workflows/publish.yml
.github/workflows/release-please.yml
.github/workflows/semgrep.yml
.github/workflows/stale.yaml
.github/workflows/test.yml

chore(ci): add link checker, reformat actions code

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/renovate.json5

chore(ci): update issue templates, renovate config

---

.gitignore
howtos/cloud-init/README.md
howtos/cloud-init/cutom/cloud-config.tf
howtos/cloud-init/cutom/main.tf
howtos/cloud-init/cutom/provider.tf
howtos/cloud-init/cutom/variables.tf

fix(docs): update HOW-TOs for cloud-init

---

docs/data-sources/virtual_environment_group.md
docs/data-sources/virtual_environment_pool.md
docs/data-sources/virtual_environment_user.md
docs/data-sources/virtual_environment_vms.md
docs/resources/virtual_environment_cluster_firewall.md
docs/resources/virtual_environment_cluster_firewall_security_group.md
docs/resources/virtual_environment_container.md
docs/resources/virtual_environment_file.md
docs/resources/virtual_environment_firewall_ipset.md
docs/resources/virtual_environment_firewall_options.md
docs/resources/virtual_environment_firewall_rules.md
docs/resources/virtual_environment_group.md
docs/resources/virtual_environment_hosts.md
docs/resources/virtual_environment_pool.md
docs/resources/virtual_environment_user.md
docs/resources/virtual_environment_vm.md

Fix for https://github.com/bpg/terraform-provider-proxmox/issues/953
Current Doc from https://registry.terraform.io/providers/bpg/proxmox/latest/docs/resources/virtual_environment_vm#cpu
With the fix and re-render from https://registry.terraform.io/tools/doc-preview:
Closes #953

fix(docs): Inconsistent indentations in docs

---

docs/index.md
proxmox/ssh/client.go
proxmoxtf/resource/vm.go

The provider now shows the following error if non-root user is configure for ssh, and it is not in sudoers, or sudo is not installed.
Root user still works without installed sudo.
Closes #962

fix(vm): regression: `sudo: command not found` when creating a VM

---

docs/index.md
fwprovider/provider.go
fwprovider/tests/resource_file_test.go
proxmox/ssh/client.go
proxmoxtf/provider/provider.go
proxmoxtf/provider/schema.go

When using this `ssh` config block, I was able to connect to the PVE node via `microsocs` SOCKS5 proxy, and successfully deploy a VM with a custom disk:
```terraform
ssh {
agent           = true
username        = "terraform"
socks5_server   = "X.X.X.99:1080"
socks5_username = "user"
socks5_password = "password"
}
```
Closes #887

feat(provider): add SOCKS5 proxy support for SSH connections

---

CONTRIBUTING.md
README.md

fix(docs): fix broken links

---

docs/guides/cloud-image.md
docs/guides/cloud-init.md
docs/guides/setup-proxmox-for-tests.md
docs/index.md
release-please-config.json

fix(docs): fix documentation tree structure in the TF registry

---

docs/index.md

docs: update sudo configuration to a more restrictive variant

---

proxmoxtf/resource/file.go

When trying to create a file using `proxmox_virtual_environment_file` we got an error:
```terraform
resource "proxmox_virtual_environment_file" "cloud_config" {
content_type = "snippets"
node_name    = var.proxmox_node_name
overwrite    = true
source_file {
path      = "cloudinit.yaml"
file_name = "debian12.cloud-config.yaml"
}
}
```
```
Error: error moving file: rm: cannot remove '...': No such file or directory
```
As discussed on (#1011) The use of `rm -rf` on tempFileDir solves the problem and also cleanup temp folder. …

fix: snippets upload

---

.golangci.yml
.mergify.yml

chore(ci): update mergify config to auto-approve renovate PRs

---

.mergify.yml

This change has been made by @bpg from Mergify config editor.

misc(ci): update .mergify.yml

---

examples/guides/cloud-image/centos-qcow2/main.tf
examples/guides/cloud-image/ubuntu-img/main.tf

chore(docs): update links disk image link in examples

---

.golangci.yml
fwprovider/tests/resource_vm_test.go
proxmoxtf/resource/cluster/firewall/firewall.go
proxmoxtf/resource/container/container.go
proxmoxtf/resource/file.go
proxmoxtf/resource/firewall/options.go
proxmoxtf/resource/firewall/rules.go
proxmoxtf/resource/validators/file.go
proxmoxtf/resource/validators/file_test.go
proxmoxtf/resource/validators/firewall.go
proxmoxtf/resource/validators/network.go
proxmoxtf/resource/validators/network_test.go
proxmoxtf/resource/vm/disk/disk.go
proxmoxtf/resource/vm/disk/schema.go
proxmoxtf/resource/vm/vm.go
proxmoxtf/resource/vm/vm_test.go
utils/maps.go

chore(vm): refactor: move disks code out of vm.go

---

.github/workflows/golangci-lint.yml
.github/workflows/test.yml
docs/guides/cloud-image.md
docs/resources/virtual_environment_download_file.md
example/resource_virtual_environment_download_file.tf
fwprovider/resource_download_file.go
fwprovider/tests/resource_download_file_test.go
fwprovider/tests/resource_file_test.go
fwprovider/tests/resource_vm_test.go
fwprovider/tests/test_support.go
templates/guides/cloud-image.md.tmpl
templates/guides/cloud-init.md.tmpl
templates/guides/setup-proxmox-for-tests.md.tmpl

feat(file): add `overwrite_unmanaged` attribute to `virtual_environment_download_file` resource

---

.golangci.yml
example/resource_virtual_environment_user.tf
fwprovider/tests/resource_container_test.go
fwprovider/tests/resource_download_file_test.go
fwprovider/tests/resource_linux_bridge_test.go
fwprovider/tests/resource_linux_vlan_test.go
fwprovider/tests/resource_user_test.go
fwprovider/tests/resource_vm_test.go
proxmox/access/users.go
proxmox/access/users_types.go
proxmoxtf/datasource/user.go
proxmoxtf/datasource/users.go
proxmoxtf/resource/user.go

Updated example:
```terraform
resource "proxmox_virtual_environment_user" "example" {
acl {
path      = "/vms/${proxmox_virtual_environment_vm.example.id}"
propagate = true
role_id   = "PVEVMAdmin"
}
comment         = "Managed by Terraform"
password        = "Test1234!"
user_id         = "terraform-provider-proxmox-example@pve"
expiration_date = "2035-12-31T23:59:59Z"
}
```
creates a user with expiration date set:
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull …

fix(user): `expiration_date` attribute handling

---

fwprovider/tests/datasource_version_test.go
fwprovider/tests/resource_container_test.go
fwprovider/tests/resource_download_file_test.go
fwprovider/tests/resource_file_test.go
fwprovider/tests/resource_linux_bridge_test.go
fwprovider/tests/resource_linux_vlan_test.go
fwprovider/tests/resource_options_test.go
fwprovider/tests/resource_user_test.go
fwprovider/tests/resource_vm_test.go
fwprovider/tests/test_support.go
go.mod
go.sum

chore: switch to `terraform-plugin-testing` for acceptance tests

---

.github/workflows/test.yml
Makefile
fwprovider/tests/resource_container_test.go
fwprovider/tests/resource_download_file_test.go
fwprovider/tests/resource_file_test.go
fwprovider/tests/resource_vm_test.go
fwprovider/tests/test_support.go

chore(ci): setup acceptance tests

---

docs/index.md

chore(docs): minor improvements around SSH private key usage

---

fwprovider/tests/resource_vm_test.go

fix(ci): TestAccResourceVMNetwork acc test fails when run on CI

---

fwprovider/provider.go
proxmoxtf/provider/schema.go

fix: allow LDAP realm API tokens

---

proxmox/nodes/vms/vms.go

Resizing fails after cloning VM into a directory.
Simple three attempt loop fix.
Usually have success on second attempt, the loop breaks.
A successul resize after a 'got timeout'. 
This ultimately resulted in a successful deployment with a disk resized from 80 to 120G.
Relates #868, #995

fix(vm): timeout when resizing a disk during clone

---

main.go
proxmox/ssh/client.go

fix(provider): EOF error when closing SSH session

---

.github/workflows/publish.yml
.goreleaser.yml
terraform-registry-manifest.json

fix(ci): missing releases from HashiCorp Registry

---

.vscode/settings.json
docs/resources/virtual_environment_vm.md
fwprovider/tests/resource_vm_test.go
proxmox/nodes/vms/customstoragedevice.go
proxmox/nodes/vms/vms_types.go
proxmoxtf/resource/vm/disk/disk.go
proxmoxtf/resource/vm/disk/schema.go
proxmoxtf/resource/vm/vm.go

A VM template with the following disk section
```terraform
disk {
aio          = "native"
file_id      = proxmox_virtual_environment_download_file.ubuntu_cloud_image.id
interface    = "virtio0"
iothread     = true
discard      = "on"
size         = 20
replicate    = false
speed {
iops_read               = 100
iops_read_burstable     = 1000
iops_write              = 200
iops_write_burstable    = 2000
}
}
```
produced
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they …

feat(vm): add support for disk `aio`, `backup`, `iops*` attributes

---

docs/resources/virtual_environment_vm.md
fwprovider/tests/resource_vm_test.go
proxmox/nodes/vms/vms_types.go
proxmoxtf/resource/vm/vm.go

feat(vm): add support for `protection` attribute

---

docs/index.md

fix(doc): fix `sudo` configuration steps

---

docs/resources/virtual_environment_container.md

Changes the docs to match the schema

fix(docs): typo in `container.console` attribute `mode` -> `type`

---

docs/data-sources/virtual_environment_node.md
example/data_source_virtual_environment_node.tf
fwprovider/tests/datasource_node_test.go
proxmox/nodes/nodes.go
proxmox/nodes/nodes_types.go
proxmoxtf/datasource/node.go
proxmoxtf/provider/datasources.go

It helps to get CPU model, nubmer of cores and sockets.
relate https://github.com/bpg/terraform-provider-proxmox/issues/1148
```tf
data "proxmox_virtual_environment_node" "node" {
node_name = "node01"
}
```
tfstate:
```json
{
"mode": "data",
"type": "proxmox_virtual_environment_node",
"name": "node",
"provider": "provider[\"registry.terraform.io/bpg/proxmox\"]",
"instances": [
{
"schema_version": 0,
"attributes": {
"cpu_count": 48,
"cpu_model": "Intel(R) Xeon(R) Gold 6248R CPU @ 3.00GHz",
"cpu_sockets": 2,
"id": "node01",
"memory_available": 196692664320,
"memory_total": 540350619648,
"memory_used": 343657955328,
"node_name": "node01",
"uptime": 99127
},
"sensitive_attributes": []
}
]
},
```
- Please vote on this pull request by adding a 👍 …

feat(vm): add proxmox_virtual_environment_node datasource

---

docs/resources/virtual_environment_vm.md
example/resource_virtual_environment_vm.tf
proxmox/nodes/vms/vms_types.go
proxmoxtf/resource/vm/vm.go

Allow use hugepages for VM memory allocation.
```tf
resource "proxmox_virtual_environment_vm" "hugepages" {
...
memory {
dedicated = 188416
hugepages = "1024"
}
}
```
Memory page table on host machine:
before (without huge pages):
```shell
PageTables:       872252 kB
SecPageTables:    853344 kB
```
after:
```shell
PageTables:        14736 kB
SecPageTables:       120 kB
```
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help …

feat(vm): add support for memory `hugepages` and `keep_hugepages` attributes

---

.vscode/settings.json
fwprovider/tests/resource_vm_test.go
proxmoxtf/resource/vm/vm.go

The new test fails before the fix:
```
Error: error updating VM: received an HTTP 500 response - Reason: only root can set 'affinity' config
with proxmox_virtual_environment_vm.test_vm5,
on terraform_plugin_test.tf line 12, in resource "proxmox_virtual_environment_vm" "test_vm5":
12: 				resource "proxmox_virtual_environment_vm" "test_vm5" {
FAIL
FAIL	github.com/bpg/terraform-provider-proxmox/fwprovider/tests	5.826s
FAIL
```
and passes after:
```
ok  	github.com/bpg/terraform-provider-proxmox/fwprovider/tests	6.012s
```
- Please do not leave "+1" …

fix(vm): regressions: provider always tries to update `cpu.affinity` even if it is not specified

---

.vscode/settings.json
fwprovider/tests/datasource_node_test.go
fwprovider/tests/datasource_version_test.go
fwprovider/tests/resource_container_test.go
fwprovider/tests/resource_download_file_test.go
fwprovider/tests/resource_file_test.go
fwprovider/tests/resource_linux_bridge_test.go
fwprovider/tests/resource_linux_vlan_test.go
fwprovider/tests/resource_user_test.go
fwprovider/tests/resource_vm_test.go
fwprovider/tests/test_environment.go

chore: refactor acceptance tests

---

proxmoxtf/resource/vm/vm.go

fix(vm): panic if `initialization.user_account_keys` contains `null`

---

.github/PULL_REQUEST_TEMPLATE.md
README.md
docs/resources/virtual_environment_file.md

chore(docs): minor documentation updates

---

docs/resources/virtual_environment_vm.md
fwprovider/tests/resource_vm_test.go
proxmox/nodes/vms/vms_types.go
proxmoxtf/resource/vm/vm.go

New acceptance tests pass:
```
=== RUN   TestAccResourceVMInitialization
--- PASS: TestAccResourceVMInitialization (93.25s)
=== RUN   TestAccResourceVMInitialization/custom_cloud-init:_use_SCSI_interface
--- PASS: TestAccResourceVMInitialization/custom_cloud-init:_use_SCSI_interface (82.71s)
=== RUN   TestAccResourceVMInitialization/native_cloud-init:_upgrade_packages_by_default
--- PASS: TestAccResourceVMInitialization/native_cloud-init:_upgrade_packages_by_default (5.27s)
=== RUN   TestAccResourceVMInitialization/native_cloud-init:_do_not_upgrade_packages
--- PASS: TestAccResourceVMInitialization/native_cloud-init:_do_not_upgrade_packages (5.27s)
PASS
```
- Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-a …

feat(vm): add support for `initialization.upgrade` attribute

---

docs/resources/virtual_environment_vm2.md
fwprovider/hardwaremapping/resource_pci.go
fwprovider/tests/resource_vm2_test.go
fwprovider/types/hardwaremapping/path.go
fwprovider/types/tags/attribute.go
fwprovider/types/tags/type.go
fwprovider/types/tags/value.go
fwprovider/vm/resource.go
fwprovider/vm/resource_model.go
fwprovider/vm/resource_schema.go

chore(vm2): experiment with sets, add `tags` support

---

proxmoxtf/resource/vm/disk/disk.go
proxmoxtf/resource/vm/vm.go

fix(vm): fix timeout when resizing custom disk at create

---

fwprovider/tests/datasource_version_test.go
fwprovider/tests/resource_vm_test.go

fix(code): update acc tests to PVE 8.2

---

docs/resources/virtual_environment_acl.md
examples/resources/proxmox_virtual_environment_acl/import.sh
fwprovider/access/resource_acl.go
fwprovider/access/resource_acl_model.go
fwprovider/tests/resource_acl_test.go

fix(access): change acl internal ID from url path format to position-based format

---

fwprovider/access/resource_acl_model.go
fwprovider/access/resource_user_token.go
fwprovider/vm/resource.go
proxmox/nodes/vms/vms_types_test.go
proxmox/types/common_types.go

misc(vm): fix CustomBool conversion bug introduced in `acl` implementation

---

docs/resources/virtual_environment_vm.md
fwprovider/tests/resource_vm_test.go
proxmox/nodes/vms/vms_types.go
proxmoxtf/resource/vm/vm.go

feat(vm): remove support for `initialization.upgrade` attribute

---

proxmox/nodes/storage/content.go

fix(file): upload timeout with 596 response code

---

proxmox/nodes/tasks/tasks.go
proxmox/nodes/vms/vms.go

fix(vm): allow `clone` to pass with warnings

---

docs/resources/virtual_environment_vm.md
fwprovider/test/resource_vm_test.go
proxmox/nodes/vms/vms_types.go
proxmoxtf/resource/vm/validators.go
proxmoxtf/resource/vm/vm.go

```hcl
vga {
type      = "qxl"
clipboard = "vnc"
}
```
Closes #1038
Closes #1320

feat(vm): add support for `vga.clipboard`, `virtio-gl` type

---

docs/resources/virtual_environment_container.md
proxmoxtf/resource/container/container.go

fix(lxc): `mount_point.backup` should be `false` by default

---

docs/index.md

docs(provider): document expectations for the default `root` shell on PVE nodes

---

proxmox/nodes/vms/vms_types.go
proxmoxtf/resource/vm/vm.go

This was tested locally to add a usb device via cluster mapping to a VM, without requiring the host parameter.
Closes #888

fix(vm): host parameter is optional if using mapping for usb

---

example/resource_virtual_environment_vm.tf
fwprovider/test/resource_vm_test.go
fwprovider/vm/vga/resource_test.go
proxmoxtf/resource/vm/vm.go

fix(vm): regression: `vga.clipboard` attribute check

---

proxmoxtf/resource/container/container.go
proxmoxtf/resource/vm/vm.go

fix(lxc,vm): fix panics when a resource block is empty

---

proxmoxtf/resource/role.go
proxmoxtf/resource/user.go

fix(access): fix `user` and `role` import

---

example/resource_virtual_environment_container.tf
example/resource_virtual_environment_download_file.tf
example/variables.tf
proxmox/nodes/tasks/tasks.go
proxmox/nodes/vms/vms.go
tools/go.sum

fix(vm): ignore 599 task status response when waiting for VM start

---

docs/resources/virtual_environment_vm.md
docs/resources/virtual_environment_vm2.md
fwprovider/vm/cdrom/resource_schema.go

chore(docs): clarify `disk.file_id` format

---

fwprovider/ha/resource_hagroup.go
fwprovider/ha/resource_haresource.go
fwprovider/test/resource_file_test.go
proxmox/nodes/vms/custom_vga_device.go
proxmoxtf/resource/validators/file.go
proxmoxtf/resource/vm/vm.go

chore(code): fix code inspection warnings

---

docs/resources/virtual_environment_vm.md

fix(docs): update virtual_environment_vm.md

---

docs/resources/virtual_environment_vm.md
tools/go.sum

fix(docs): add more details about the `usb` block in VM

---

proxmoxtf/resource/container/container.go

This removes the default `vm_id` of `-1` for containers and computes the value instead. It looks like this was implemented for vms in PR [#367](https://github.com/bpg/terraform-provider-proxmox/pull/367) but not for the container code.
I was not able to run `make test` successfully as it requires local-lvm which I am not using. I did manually test creating a container which applied successfully.
[tf-plan.txt](https://github.com/user-attachments/files/15781593/tf-plan.txt)
[tf-apply.txt](https://github.com/user-attachments/files/15781592/tf-apply.txt)
- Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this …

fix(lxc): make container vm_id computed

---

proxmoxtf/resource/vm/vm.go

chore(vm): fix regression after storage devices refactoring

---

.github/workflows/test.yml
.github/workflows/testacc.yml
.golangci.yml
Makefile
fwprovider/access/resource_acl_test.go
fwprovider/access/resource_user_test.go
fwprovider/hardwaremapping/resource_hardware_mapping_test.go
fwprovider/network/resource_linux_bridge_test.go
fwprovider/network/resource_linux_vlan_test.go
fwprovider/resource_download_file_test.go
fwprovider/resource_options_test.go
fwprovider/test/datasource_node_test.go
fwprovider/test/datasource_version_test.go
fwprovider/test/resource_container_test.go
fwprovider/test/resource_file_test.go
fwprovider/test/resource_firewall_test.go
fwprovider/test/resource_time_test.go
fwprovider/test/resource_vm_cdrom_test.go
fwprovider/test/resource_vm_disks_test.go
fwprovider/test/resource_vm_test.go
fwprovider/test/test_environment.go
fwprovider/vm/cdrom/resource_test.go
fwprovider/vm/cpu/resource_test.go
fwprovider/vm/resource_test.go
fwprovider/vm/vga/resource_test.go
proxmoxtf/resource/container/container.go

chore: refactor container acc test

---

fwprovider/test/resource_time_test.go
proxmoxtf/resource/time.go

fix(time): embed timezone data to fix set/get TZ on windows 

---

tools/tools.go

Before this change the `make docs` command would cause the generated guides directory to be nested in `docs/guides/guides`.

fix(tools): ensure docs/guides files are copied correctly

---

.devcontainer/devcontainer.json
.devcontainer/post-attach.sh

feat(devcontainer): configure provider override in post attach command

---

proxmoxtf/resource/firewall/ipset.go

```hcl
resource "proxmox_virtual_environment_firewall_ipset" "test_ipset" {
name    = "test-ipset"
dynamic "cidr" {
for_each = range(20)
iterator = idx
content {
name    = "192.168.0.${idx.value}"
}
}
}
```
```
+ create
+ resource "proxmox_virtual_environment_firewall_ipset" "test_ipset" {
+ id   = (known after apply)
+ name = "test-ipset"
+ cidr {
+ name    = "192.168.0.0"
+ nomatch = false
}
+ cidr {
+ name    = "192.168.0.1"
+ nomatch = false
}
+ cidr {
+ name    = "192.168.0.2"
+ nomatch = false
}
+ cidr {
+ name    = "192.168.0.3"
+ nomatch = false
}
+ cidr {
+ name    = "192.168.0.4"
+ nomatch = false
} …
```

fix(firewall): remove limit for number of CIRDs in `ipset`.

---

docs/resources/virtual_environment_vm.md

Typo in example usage of using downloaded iso for disk

fix(doc): update virtual_environment_vm.md

---

docs/index.md

fix(docs): improve "SSH User" section describing `sudo` privileges

---

fwprovider/test/resource_vm_cdrom_test.go

chore(vm): add acc test for no cdrom by default

---

fwprovider/network/resource_linux_vlan_test.go
proxmoxtf/resource/vm/vm.go
proxmoxtf/resource/vm/vm_test.go

feat(vm): remove deprecated `vga.enabled`

---

docs/resources/virtual_environment_network_linux_bridge.md
examples/resources/proxmox_virtual_environment_network_linux_bridge/resource.tf

chore(docs): improve `network_linux_bridge` documentation

---

docs/resources/virtual_environment_vm.md

chore(docs): add example for host disk pass-through to VM

---

docs/resources/virtual_environment_container.md

fix:typo in container guide

---

README.md

fix(docs): update README.md 

---

docs/guides/cloud-image.md
templates/guides/cloud-image.md.tmpl

fix(docs): typo in cloud-image.md guide, exiting -> existing

---

.github/FUNDING.yml
.github/ISSUE_TEMPLATE/bug_report.md
README.md

misc(docs): minor project docs update

---

example/test-api-creds-auth/example.tfrc

not much to say, i missed a file and here it is

fix(tests): add missing example.tfrc to test api-authentication folder

---

docs/resources/virtual_environment_file.md

chore(docs): clarify use of `dump` content type in`proxmox_virtual_environment_file` resource

---

proxmox/cluster/id_generator.go

Signed-off-by: Pavel Boldyrev <627562+bpg@users.noreply.github.com>
Relates #1610

feat(provider): better error logging when provider can't generate a VM/Container ID

---

docs/resources/virtual_environment_download_file.md
fwprovider/resource_download_file.go

I haven't run `make example`, the only PVE instance I have access to is hill. configured to run it.
But I did test the change with an existing/working `main.tf`.
Also I read [CONTRIBUTING.md](https://github.com/bpg/terraform-provider-proxmox/blob/main/CONTRIBUTING.md) an tried to follow it.
Closes #1513 | Relates #0000

feat(vm): add bz2 (bzip2) as a valid download file compression algorithm

---

docs/resources/virtual_environment_container.md
fwprovider/test/resource_container_test.go
proxmox/nodes/containers/containers_types.go
proxmoxtf/resource/container/container.go
proxmoxtf/resource/container/container_test.go

``` hcl
device_passthrough {
deny_write = false
gid        = 44
mode       = "0777"
path       = "/dev/dri/card0"
uid        = 0
}
device_passthrough {
deny_write = false
gid        = 104
mode       = "0777"
path       = "/dev/dri/renderD128"
uid        = 0
}
```
Closes #1530

feat(lxc): add support for `device_passthrough` config option

---

fwprovider/test/resource_container_test.go
proxmoxtf/resource/container/container.go

Debug log on LXC resource create:
```
2025-01-20T23:36:57.829+0700 [DEBUG] provider.terraform-provider-proxmox_v0.70.0: Sending HTTP Request: 
Host=pve1.dhimas.net:8006
tf_http_req_method=POST
tf_provider_addr=registry.terraform.io/bpg/proxmox
tf_resource_type=proxmox_virtual_environment_container
@caller=/home/gifary/.asdf/installs/golang/1.23.3/packages/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.35.0/helper/logging/logging_http_transport.go:162
Content-Type=application/x-www-form-urlencoded
Csrfpreventiontoken=678E7BA9:Cwo7LdHSwZ2gvbIXX0Rz36J2/YuWPE0Wl4D7idsQMZY
tf_http_req_body="arch=amd64&cmode=tty&console=1&cores=2&cpuunits=100&description=Managed+by+OpenTofu&dev0=deny-write%3D0%2Cpath%3D%2Fdev%2Fdri%2FrenderD128%2Cuid%3D0%2Cgid%3D104%2Cmode%3D0777&features=mount%3Dnfs%2C …
```

fix(lxc): support `device_passthrough` config on non-clone container

---

docs/resources/virtual_environment_vm.md
proxmoxtf/resource/vm/validators.go
proxmoxtf/resource/vm/validators_test.go

References:
- https://pve.proxmox.com/pve-docs/api-viewer/#/nodes/{node}/qemu
- https://wiki.qemu.org/Features/VT-d
Closes #1749

fix(vm): fix vm machine type validation in order to support viommu

---

proxmoxtf/resource/container/container.go

I checked https://pve.proxmox.com/pve-docs/api-viewer/index.html#/nodes/{node}/lxc/{vmid}/config and there doesn't seem to be any limit there. This just changes the constant that controls the limit to a value high enough that the limit shouldn't be a problem to anyone, I checked the code and that seems to be the only needed change.
Relates …

feat(lxc): increase maximum supported passthrough devices to 128

---

docs/resources/virtual_environment_cluster_firewall_security_group.md

fix(docs): firewall security group typo `enabled`

---

docs/resources/virtual_environment_cluster_firewall_security_group.md
docs/resources/virtual_environment_firewall_rules.md
proxmoxtf/resource/firewall/rules.go

Thoughts on where I might add a warning to the docs similar to the Proxmox UI?
> Forward rules only take effect when the nftables firewall is activated in the host options
Tested change via "Manual Testing" process in CONTRIBUTING.md.
```
terraform {
required_version = ">= 1.12.2"
required_providers {
proxmox = {
source  = "dev.com/bpg/proxmox"
}
}
}
provider "proxmox" {}
resource "proxmox_virtual_environment_firewall_rules" "test" {
rule {
type    = "forward"
action  = "ACCEPT"
comment = "testing"
source  = "10.42.0.10"
dest    = "10.43.0.10"
}
}
```
- Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this …

feat(firewall): adds forward type to firewall rules

---

.devcontainer/Dockerfile
docs/resources/virtual_environment_apt_standard_repository.md
fwprovider/nodes/apt/resource_standard_repo.go

N/A - Documentation change only
Closes #2044

chore(docs): add ceph squid to `apt_standard_repository` docs

---

proxmoxtf/resource/container/container.go

The limit now matches the number of network interfaces allowed by Proxmox
Closes #2080

fix(lxc): adjust max number of container's IP configs

---

.golangci.yml
fwprovider/cluster/acme/datasource_acme_plugin_test.go
fwprovider/cluster/sdn/applier/resource.go
proxmox/cluster/firewall/options_types.go
proxmox/cluster/sdn/zones/doc.go
proxmox/helpers/ptr/ptr.go
proxmox/nodes/containers/containers_types.go
proxmox/nodes/vms/custom_agent.go
proxmox/nodes/vms/custom_amdsev.go
proxmox/nodes/vms/custom_cpu_emulation.go
proxmox/nodes/vms/custom_efi_disk.go
proxmox/nodes/vms/custom_network_device.go
proxmox/nodes/vms/custom_numa_device.go
proxmox/nodes/vms/custom_pci_device.go
proxmox/nodes/vms/custom_rng_device.go
proxmox/nodes/vms/custom_storage_device.go
proxmox/nodes/vms/custom_usb_device.go
proxmox/nodes/vms/custom_virtiofs_share.go

chore(code): minor code cleanups

---

README.md

chore(docs):  include vm/lxc lock error details in the README known issues section

---

fwprovider/test/resource_firewall_test.go
proxmoxtf/resource/firewall/rules.go
proxmoxtf/resource/firewall/rules_test.go

See new acceptance tests.
Closes #1505

fix(firewall): detect drift when rules are manually deleted

---

fwprovider/cluster/sdn/subnet/model.go
fwprovider/cluster/sdn/subnet/resource.go
fwprovider/cluster/sdn/subnet/resource_test.go

fix(sdn): subnet validation errors when using value interpolation

---

docs/data-sources/virtual_environment_sdn_zones.md
docs/resources/virtual_environment_sdn_zone_simple.md
fwprovider/cluster/sdn/zone/datasource_zones.go
fwprovider/cluster/sdn/zone/resource_simple.go
proxmox/cluster/sdn/zones/zones_types.go

The current implementation of the simple Zone SDN is missing the `automatic DHCP` [option which enables DHCP using `dnsmasq`](https://pve.proxmox.com/wiki/Setup_Simple_Zone_With_SNAT_and_DHCP).
I added the option in a similar fashion as other attributes for specific zones in the resource. The API mentions this is an enum but currently only dnsmasq or nothing is supported. When configured in the simple zone resource, it's added to the zone configuration, which in turns tick the checkbox in the UI:
```
resource "proxmox_virtual_environment_sdn_zone_simple" "sdn_zone_priv01" {
id    = "znpriv01"
nodes = ["pve01"]
ipam = "pve"
dhcp = "dsmasq"
depends_on = [
proxmox_virtual_environment_sdn_applier.finalizer
]
}
```
Deletion currently as the same issue as other attributes of SDN resources, as …

feat(sdn): Add DHCP Config for SDN Simple Zone Resource
