README.md
Recent changes in the provider to make it compatible with Proxmox v7.x broke backward compatibility with previous versions, as was reported in #30.
This PR does not introduce any changes in the provider's functionality.
- Update README.md to indicate version compatibility with PVE
=> Bump provider version to 0.5.0

proxmox/virtual_environment_datastores.go
During the setup of this Terraform module, I was trying to create a cloud-init template based on [this example](https://github.com/bpg/terraform-provider-proxmox/blob/main/example/resource_virtual_environment_file.tf). I noticed that when trying to retrieve the datasource path for NFS mounts, it was failing with the following error: 
```
proxmox_virtual_environment_file.ubuntu_cloud_config["lrhq-ubuntu-test01"]: Creating...
proxmox_virtual_environment_file.test: Creating...
╷
│ Error: Failed to determine the datastore path
│ 
│   with proxmox_virtual_environment_file.ubuntu_cloud_config["lrhq-ubuntu-test01"],
│   on files.tf line 1, in resource "proxmox_virtual_environment_file" "ubuntu_cloud_config":
│    1: resource "proxmox_virtual_environment_file" "ubuntu_cloud_config" {
│ 
╵
╷
│ …
```
=> virtual_environment_datastores.go: Update remote command to get datasource path

Makefile, proxmoxtf/resource_virtual_environment_vm.go
The disk import operation is not exposed via Proxmox APIs, so implemented as a sequence of commands run as an inline script via ssh.
`qm importdisk` is used to import a disk into VM from an external file, however, it auto-generates the disk ID.
The following command `qm set` is used to assign the imported disk to a VM, and it requires the disk ID as a parameter.
Update the import logic to read the disk ID from the output of `qm importdisk` command rather than trying to assume it from a number of disks defined in the VM.
* Please do not leave "+1" …
=> Fix disk import when VM template has multiple disks

proxmoxtf/resource_virtual_environment_vm.go
Outputs 'ipv4_addresses', 'ipv6_addresses', 'network_interface_names' of
stopped VM are empty and break plans - e.g. search for "eth0" in empty list.
On update, mark them 'Computed' if there is planned change in 'started'
or 'network_device' of the VM.
This makes it possible to depend on e.g. 'network_interface_names' of VM
which is not running at the time of 'terraform plan', but which will be
started during 'terraform apply'.
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra …
=> Provide correct outputs from stopped VM

proxmox/virtual_environment_vm.go
VM can get IPv6 link-local address faster than a DHCP server response,
that results in 'ipv4_addresses' output being an empty list.
It is then impossible to provision the VM using 'connection.host' field
derived from 'self.ipv4_addresses'.
Change the waiting for IP address to ignore IPv4 link-local addresses
and IPv6 link-local addresses.
Closes #100
=> Wait for 'net.IsGlobalUnicast' IP address

example/resource_virtual_environment_vm.tf, go.mod, proxmox/virtual_environment_vm_types.go, proxmox/virtual_environment_vm_types_test.go, proxmoxtf/version.go
Fix disk format parsing from the volume string.
Add basic unit tests for disk volume string parsing.
Closes: https://github.com/bpg/terraform-provider-proxmox/issues/129
=> fix: Non-default VM disk format is not preserved in TF state

example/resource_virtual_environment_container.tf, proxmoxtf/resource_virtual_environment_container.go
=> fix: handling `datastore_id` in LXC template

example/resource_virtual_environment_vm.tf, proxmox/virtual_environment_vm.go
This allows us to have multiple interfaces and only one (instead of all) has to have assigned ip
Closes #164
=> fix: Check if any interface has global unicast address instead of all interfaces

docs/resources/virtual_environment_container.md, docs/resources/virtual_environment_vm.md, example/resource_virtual_environment_container.tf, example/resource_virtual_environment_vm.tf, proxmox/virtual_environment_vm_types.go, proxmoxtf/resource_virtual_environment_container.go, proxmoxtf/resource_virtual_environment_container_test.go, proxmoxtf/resource_virtual_environment_vm.go, proxmoxtf/resource_virtual_environment_vm_test.go
=> feat: add support for network_device MTU

docs/resources/virtual_environment_vm.md, proxmoxtf/resource_virtual_environment_vm.go
Hi,
The `on_boot` parameter is used to start a VM when the node reboots. As the VM infrastructure should not really care whether an hypervisor has rebooted, we change the default value from `false` to `true` in order to make it explicit not to start the VM on reboot.
Cheers
Signed-off-by: Frank Villaro-Dixon <frank@villaro-dixon.eu>
=> feat(vm): OnBoot: change default to `true`

docs/resources/virtual_environment_vm.md, proxmox/virtual_environment_vm_types.go, proxmoxtf/resource_virtual_environment_vm.go
Adds the option to specify a `network-config` cloud-init file just like you can already specify user/vendor data.
The currently provided `ip_config` blocks under the `initialization` block for the VM resource are rather limited, and implementing all possible network options and features would not really make sense. With this modifications users can write the cloud-init network config file themselves if they want to, supporting way more advanced network setups.
Using it is the same as with the user/vendor data files;
```
resource "proxmox_virtual_environment_vm" "instance" {
#...
user_data_file_id      = proxmox_virtual_environment_file.cloud_config_user.id
network_data_file_id = proxmox_virtual_environment_file.cloud_config_network.id
}
}
```
The backend code already …
=> feat(vm): Add cloud-init network-config support

docs/resources/virtual_environment_vm.md, proxmox/virtual_environment_vm_types.go, proxmoxtf/resource_virtual_environment_vm.go, proxmoxtf/resource_virtual_environment_vm_test.go
1. You need first a template and a qcow2 image:
```
mkdir -p /root/download/
cd /root/download/
wget https://download.opensuse.org/tumbleweed/appliances/openSUSE-MicroOS.x86_64-ContainerHost-kvm-and-xen.qcow2
qm create 1001 --name opensuse-microos --memory 4098 --cores 4
qm importdisk 1001 …
```
=> feat(vm): add support for "args" flag for VM

docs/resources/virtual_environment_container.md, example/resource_virtual_environment_container.tf, proxmoxtf/resource_virtual_environment_container.go, proxmoxtf/resource_virtual_environment_container_test.go
A great project, thanks.
I am currently working on automating my small homelab. I am using VM and container tags to build an ansible inventory dynamically and missed the `tags` parameter for containers. 
This PR is merely an adaptation of https://github.com/bpg/terraform-provider-proxmox/pull/169 for LXC containers.
=> feat(lxc): Add support for container tags

proxmoxtf/resource_virtual_environment_vm.go
When I try to clone from a template with no `hostpci` in the config, the post body would contain an extra `hostpci` because of these lines (from `DefaultFunc`).
---
=> fix(vm): Don't add an extra hostpci entry

docs/resources/virtual_environment_container.md, proxmoxtf/resource_virtual_environment_container.go, proxmoxtf/resource_virtual_environment_container_test.go
Currently you cannot set `unprivileged` in `proxmox_virtual_environment_container`. I believe this adds the option to do so (I've not contributed to a provider before).
Relates #224
=> feat(lxc): Add unprivileged option

proxmoxtf/resource_virtual_environment_vm.go
=> fix(vm): Fix handling of empty kvm arguments

proxmoxtf/resource_virtual_environment_file.go
This triggers "changed outside of Terraform" detection on the resource when Terraform re-applies the same plan second time.
=> fix(vm): `proxmox_virtual_environment_file.changed` stored as `true` at file creation

example/resource_virtual_environment_vm.tf, proxmox/virtual_environment_nodes.go, proxmoxtf/resource_virtual_environment_vm.go
Update [shell scripting](https://github.com/bpg/terraform-provider-proxmox/issues/187#issuecomment-1363594575) responsible for disk imports.
Tested with
```terraform
data "local_file" "ssh_public_key" {
filename = "./id_rsa.pub"
}
resource "proxmox_virtual_environment_file" "cloud_config" {
content_type = "snippets"
node_name    = var.virtual_environment_node_name
source_raw {
data = <<EOF
#cloud-config
users:
- default
- name: ubuntu
groups:
- sudo
shell: /bin/bash
ssh_authorized_keys:
- ${trimspace(data.local_file.ssh_public_key.content)}
sudo: ALL=(ALL) NOPASSWD:ALL
runcmd:
- apt update
- apt install -y qemu-guest-agent net-tools
- timedatectl set-timezone America/Toronto
- systemctl enable qemu-guest-agent
- systemctl start qemu-guest-agent
- echo "done" > …
```
=> feat(vm): update VM disc import logic

.github/workflows/test.yml, Makefile, example.tfrc, example/versions.tf
=> fix(build): Fix make example-init for TF 1.4

docs/index.md, example/main.tf, proxmoxtf/provider/provider.go, proxmoxtf/provider/provider_test.go, proxmoxtf/provider/schema.go
Also deprecate virtual_environment block, update docs and examples.
Not sure if there is any reason for keeping it.
Fixes #117 
Apparently CDKTF skips schemas without attributes, it has been fixed but it is available only in prerelease currently (https://github.com/hashicorp/terraform-cdk/pull/2736)
* Please do not leave "+1" or other comments that do not add relevant new information or questions, …
=> fix(provider): Deprecate `virtual_environment` block

docs/resources/virtual_environment_container.md, docs/resources/virtual_environment_vm.md, proxmoxtf/resource/container.go, proxmoxtf/resource/vm.go
=> fix(firewall): Add support for `firewall` flag for LXC/VM net adapters

proxmox/virtual_environment_vm.go, proxmox/virtual_environment_vm_types.go, proxmoxtf/resource/vm.go
The current implementation of the VM creation flow in the provider does not wait until the VM is created by PVE, nor does it handle a response from the `Create VM` API call. Ignoring the error API response can cause #211 because the VM is not created, and the VM ID is not available for the provider to read from. This causes the provider to reset the state to empty, resulting in an "inconsistent result after apply" error.
The added sync functionality may also improve behaviour in #186, although this use case has not been tested yet.
* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to …
=> feat(vm): Wait for the VM creation task to complete

.github/ISSUE_TEMPLATE/bug_report.md, proxmox/datastores.go, proxmox/datastores_types.go, proxmox/virtual_environment_nodes.go, proxmoxtf/resource/file.go
=> fix(file): SSH file upload on Windows

proxmoxtf/resource/vm.go
`make examples` does not exist, I guess it should be `make example`
Was weird having a diff with network_device on firewall enabled after update, docs state default false
=> fix(firewall): use correct default value for firewall

Makefile
=> chore(make): Add `lint`, `release-build` targets

proxmox/types/common_types.go, proxmox/types/disk_size.go, proxmox/types/disk_size_test.go, proxmox/types/helpers.go, proxmox/utils.go, proxmox/utils_test.go, proxmox/virtual_environment_container_types.go, proxmox/virtual_environment_vm_types.go, proxmox/virtual_environment_vm_types_test.go, proxmoxtf/resource/container.go, proxmoxtf/resource/vm.go
Relates to #86 as previously discussed.
Closes #314
=> feat(vm,lxc): Improved support for different disk size units

proxmox/types/disk_size.go, proxmox/types/disk_size_test.go
=> fix(vm): Regression: cannot create disks larger than 99G

Makefile, README.md, go.mod, tools/go.mod
Bumping the go version ensures that MacOS DNS is resolved correctly as per https://go-review.googlesource.com/c/go/+/446178.
Resolves: #341
Closes #0000
=> feat: bump Go to 1.20 to resolve MacOS DNS resolution issues

proxmox/virtual_environment_vm.go
VM can get IPv6 link-local address faster than a DHCP server response, that results in 'ipv4_addresses' output being an empty list. It is then impossible to provision the VM using 'connection.host' field derived from 'self.ipv4_addresses'.
Once again change waiting for IP address to wait for better address than IPv4 link-local addresses and IPv6 link-local addresses.
Should not break #182, because it requires only one GlobalUnicast address per VM.
* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the …
=> fix(vm): Regression: wait for 'net.IsGlobalUnicast' IP address  (#100)

proxmoxtf/resource/vm.go
Fields `network_interface_names`, `ipv4_addresses` and `ipv6_addresses` are sometimes be marked `computed` again, using `CustomizeDiff`. Changes in `VMStarted` or `VMNetworkDevice` attributes invalidate those values. Marking fields `computed` again avoids stale values.
`network_device` configuration block without `mac_address` results in MAC address set to its default value (an empty string). Terraform state expects `mac_address` to be an empty string, server provides the actual (random) MAC address of the network device. Terraform detects there are changes to be made, but because of `DiffSuppressFunc` on `mac_address` they are hidden from the user, but not from d.HasChange(mkResourceVirtualEnvironmentVMNetworkDevice)
By making `mac_address` also `computed`, the server-generated MAC …
=> fix(vm): Make mac_address computed, fix #339

proxmoxtf/resource/firewall/selector.go
Make sure VM / Container rules, SGs, IPSets are always include `node_name` along with `vm_id`, `container_id`.
New validation rule:
```
╷
│ Error: Missing required argument
│
│   with proxmox_virtual_environment_firewall_rules.vm_rule_sg,
│   on main.tf line 210, in resource "proxmox_virtual_environment_firewall_rules" "vm_rule_sg":
│  210:   vm_id     = proxmox_virtual_environment_container.example.vm_id
│
│ "vm_id": all of `node_name,vm_id` must be specified
```
* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request …
=> fix(firewall): Improve firewall resources argument validation

docs/resources/virtual_environment_firewall_ipset.md
I tried to add an ipset following the docs in https://github.com/bpg/terraform-provider-proxmox/blob/main/docs/resources/virtual_environment_firewall_ipset.md but I got this error:
```
Error: Invalid resource type
│
│   on infra/proxmox-firewall/cluster-wide-ipsets.tf line 1, in resource "proxmox_virtual_environment_cluster_firewall_ipset" "admin_hosts":
│    1: resource "proxmox_virtual_environment_cluster_firewall_ipset" "admin_hosts" {
│
│ The provider bpg/proxmox does not support resource type "proxmox_virtual_environment_cluster_firewall_ipset".
```
Reviewing the code I noticed that the resource name is `proxmox_virtual_environment_firewall_ipset` and not `proxmox_virtual_environment_cluster_firewall_ipset` as mentioned in the docs. This PR fixes the docs.
It works when using …
=> fix(docs): Update documentation for resource `proxmox_virtual_environment_firewall_ipset`

proxmoxtf/provider/provider_test.go, proxmoxtf/provider/schema.go, proxmoxtf/test/test_utils.go
Allow using repeated 'node' blocks in ssh configuration.
Relates to #355
=> fix(core): Do not limit cluster size to 1 in provider's `ssh` config

docs/resources/virtual_environment_container.md, example/resource_virtual_environment_container.tf, example/resource_virtual_environment_vm.tf, proxmoxtf/resource/vm.go
Defaulting vm_id to -1 prevents resources depending on vm_id value. Make vm_id computed, also update existing vm_id = -1 with correct vm_id.
Closes #364
=> fix(vm): Make `vm_id` computed

proxmoxtf/resource/file.go
Error like may pop up when uploading a file over SSH (snippets is the most common use case), when the storage in fact has "snippets" type enabled.
> Warning: the datastore "local" does not support content type "snippets"
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize …
=> fix(file): spurious unsupported content type warning

proxmox/api/authenticator.go, proxmox/api/client.go, proxmox/api/ticket_auth.go, proxmox/api/token_auth.go, proxmoxtf/resource/vm.go
Token logins using root@pam!sometoken=uuid are not considered by PVE as 'root' logins, and fail to change VM's arch. Make sure the provider does not try to set/change VM's arch.
=> fix(provider): Better handling of root@pam token

proxmox/cluster/cluster.go, proxmoxtf/resource/vm.go
=> fix(vm): do not error on `read` at state refresh if VM is missing

proxmox/nodes/network_types.go
There is inconsistency in PVE API between versions, so ignore the field altogether as it is not used anywhere at the moment. 
Relates: #410
=> fix(node): ignore field `bridge_fd` when listing network interfaces of a node

proxmox/nodes/vms/vms_types.go
Finally found the missing piece and just went ahead and added it myself for enough json parsing support to make the parse error go away so that vm imports will succeed when startup options are configured. …
=> fix(vm): add missing unmarshal for vm custom startup order

proxmoxtf/resource/vm.go
Ignore empty storage devices which may not have any media mounted, or the API will throw an error.
---
=> fix(vm): fix for the api call upon empty disks

proxmoxtf/resource/vm.go
When I tried to clone from a template with the default bios setting (`seabios`), there should be no `efi_disk` in the config. However, the post body would contain an extra `efi_disk` due to these lines (from `DefaultFunc`).
I believed this issue was like https://github.com/bpg/terraform-provider-proxmox/pull/223.
---
=> fix(vm): Don't add an extra efi_disk entry

docs/resources/virtual_environment_vm.md, example/resource_virtual_environment_vm.tf, proxmoxtf/resource/vm.go
```terraform
startup {
order      = "3"
up_delay   = "60"
down_delay = "60"
}
```
Closes #392
=> feat(vm): add support for start/shutdown order configuration

proxmoxtf/resource/vm.go
`cache` should be one of [none writethrough writeback unsafe directsync], the default "" is given, however.
---
=> fix(vm): give `cache` the correct default value

docs/resources/virtual_environment_user.md, proxmoxtf/resource/user.go, proxmoxtf/resource/user_test.go
=> fix(user): make `password` attribute optional

proxmox/api/client.go
The HTTP client makes requests using the operational context passed from Terraform. The client will no longer enforce its own fixed timeout but will rely on context cancellation instead.
Closes #426
=> fix(API): remove HTTP client timeout

Makefile, docs/resources/virtual_environment_file.md, proxmox/nodes/storage.go, proxmoxtf/resource/file.go, proxmoxtf/resource/file_test.go
The upload of ISO/VMTMPLs uses the Proxmox REST API Upload. But as the code doesn't wait for this to finish you can run into problems deploying the VM
We saw this when creating multiple VMs that were using a "proxmox_virtual_environment_file" to point to our Ubuntu image (~6GB). You could see the upload task was still running on the Proxmox node, but then started creating the VM. This led to a corrupt image that couldn't start
We've added WaitForTask for the upload so that it polls to check it really is uploaded. 
Rather that hardcode a timeout (as in network.go) we've added a parameter into "proxmox_virtual_environment_file" which defaults to 1800s but can be overridden
Updated file_test.go that checks the file Schema
Tested locally and with the fix we were then able to create VMs as the …
=> feat(file): ensure upload of ISO/VSTMPL is completed upon resource creation

Makefile, proxmoxtf/resource/file.go, proxmoxtf/resource/vm.go
Also fixes missing `ForceNew` for `file` resources.
Closes #468
=> fix(vm): default disk cache is not set to `none` if not specified for an existing disk

proxmoxtf/resource/vm.go
=> fix(vm): ensure startup / shutdown delay is applied when order is not configured

proxmox/nodes/vms/vms.go
When the VM contains at least one bridge, the main interface (e.g. `eth0`) is left without an IP address because that's how networks usually work.
The code that queries the VM's IP addresses (through the guest agent), loops all available interfaces to find one. The existing code though would prematurely exit the loop if the interface it was checking had no IP address assigned. Like the aforementioned `eth0`, when it is controlled by a bridge.
This patch fixes this problem by not exiting the loop, instead just continuing to the next interface.
* Please vote on this pull request by adding a 👍 …
=> fix(vm): no IP address detection when VM contains bridges

proxmox/nodes/vms/vms_types.go, proxmox/nodes/vms/vms_types_test.go
This change fixes an index out of range error when trying to unmarshal a CustomPCIDevice from a string just containing the device id and no comma separated key/value pairs.
=> fix(vm): fix index out of range when unmarshalling custompcidevice

proxmoxtf/resource/vm.go
* This commit fixes a linter error that somehow doesn't manifest unless some other, unrelated changes trigger it (see #501 and #505).
* In addition it fixes a similar issue that had so far gone undetected by the linter.
* Refactored the code in question into a function, since it was mostly duplicated.
* Simplified a pair of conditionals that had the same code in both branches.
* Please do not leave …
=> chore(vm): fix linter errors

proxmox/pools/pool_types.go, proxmoxtf/resource/vm.go
This commit removed the `ForceNew` flag from the VM resource's `pool_id` argument and implements pool update:
* if the VM was part of a pool, it is removed from it,
* if the new `pool_id` value is non-empty, the VM is added to that new pool.
It triggers the same linter problem as my other pull request, the same [solution](https://github.com/bpg/terraform-provider-proxmox/pull/501#issuecomment-1682782500) would apply.
* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers …
=> feat(vm): pool update support

docs/resources/virtual_environment_vm.md, example/resource_virtual_environment_vm.tf, proxmox/nodes/vms/vms_types.go, proxmoxtf/resource/vm.go
* Added a `migrate` VM flag which changes the provider's behaviour when the VM's `node_name` is updated. If `true`, the VM will be migrated to the specified node instead of being re-created.
* Added a `timeout_migrate` setting to control the timeout for VM migration.
* Fixed a bug in the API's migration data structure that prevented the online migration flag to be set.
* Please do not leave "+1" or …
=> feat(vm): support for migration when the node name is modified

proxmox/api/client.go, proxmox/api/errors.go, proxmox/nodes/storage.go, proxmox/nodes/tasks/tasks.go
=> fix(core): improve error handling while waiting for PVE tasks to complete

proxmoxtf/resource/file.go
=> fix(file): forced replacement of file resources that missing `timeout_upload` attribute

internal/network/resource_linux_bridge.go, internal/test/network/resource_linux_bridge_test.go
=> fix(node): creating linux_bridge with 'vlan_aware=false' or 'autostart=false'

proxmox/nodes/tasks/client.go, proxmox/nodes/tasks/tasks.go, proxmox/nodes/tasks/tasks_types.go, proxmox/nodes/tasks/tasks_types_test.go
Improves "wait for task status" behaviour by parsing node name from the task ID and interrogating the actual node where task is being executed, and not the one the provider is connected to.
Closes #521
=> fix(node): file upload in multi-node PVE cluster

proxmoxtf/resource/validator/vm.go, proxmoxtf/resource/vm.go
The CloudInit interface can be left empty in order to allow autodetection of the drive being used. However, it would seem that this value was causing problems (see #539).
This commit adds an additional validator for CloudInit interfaces which allows the `""` value.
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull …
=> fix(vm): explicitly allow `""` as a value for CloudInit interfaces

docs/resources/virtual_environment_file.md, proxmoxtf/resource/file.go, proxmoxtf/resource/file_test.go
`proxmox_virtual_environment_file` uses the following format as a resource ID (aka `volumeID`): `datastore_id:content_type/file_name`.
However, the file `import` operation uses import ID of a slightly different format: `node_name/datastore_id/content_type/file_name` and sets the imported file resource ID as `datastore_id/content_type/file_name` at the end.
This PR updates import ID to use compatible `node_name/datastore_id:content_type/file_name` notation.
* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to …
=> feat(file): FORMAT CHANGE: update import id, so it matches the resource's format: `<node_name>/<datastore_id>:<content_type>/<file>`

.github/ISSUE_TEMPLATE/bug_report.md, .github/PULL_REQUEST_TEMPLATE.md, .github/workflows/semgrep.yml, .github/workflows/test.yml, Makefile
=> chore(ci): cleanup and update project configs

proxmox/nodes/containers/containers_types.go, proxmox/nodes/vms/vms_types.go
Note: configuring `cpulimit` via container resource attributes is not supported at the moment.
Relates OR Closes #552
=> fix(lxc,vm): error unmarshalling string `cpulimit`

proxmox/cluster/ha/resources/resources.go, proxmox/cluster/ha/resources/resources_types.go, proxmox/nodes/containers/containers_types.go, proxmox/nodes/vms/vms_types.go, proxmox/nodes/vms/vms_types_test.go, proxmoxtf/resource/container.go, proxmoxtf/resource/vm.go
They were accidentally added in #536
=> chore(code): remove redundant `types2` import aliases

CONTRIBUTING.md
=> chore(doc): add a note about DCO to CONTRIBUTING.md

docs/resources/virtual_environment_file.md, fwprovider/tests/resource_file_test.go, proxmoxtf/resource/file.go
The new `overwrite` attribute acontrol over files overwrite in the `proxmox_virtual_environment_file` resource.
**By default**, `proxmox_virtual_environment_file` resource has `overwrite = true`, and if a file with the same name already exists in the target datastore, the provider will overwrite it with printing a warning in the console:
If `overwrite = false`, the provider will throw an error:
The file being overwritten can be any datastore file, including those deployed outside of the Terraform plan.
* Please do not leave "+1" or other comments …
=> feat(file): add optional `overwrite` flag to the file resource

proxmoxtf/resource/container.go
And also fix container startup behaviour: "error starting container ... - already running"
Separately tested changing `started = true|false` in the initial template and at re-aplly 
Closes #609
=> fix(lxc): create container when authenticated with API token

proxmox/nodes/vms/vms_types.go
Storage using .raw or .qcow2 files uses additional element in path, which is not present in ZFS storage.
Support both patterns when determining disk ownership.
This fixes #632
Reproduced the error in #632, worked after the fix.
Relates OR Closes #632
=> fix(vm): better check for disk ownership

proxmoxtf/resource/vm.go
Disks imported using `file_id` argument do not have FileVolume set, that makes PathInDatastore return an empty string, which makes IsOwnedBy return fales for any vm id.
The end result is the inability to resize imported disks, this fixes it.
Successfully  resized 
```terraform
disk {
datastore_id = var.vm_datastore
file_format = "raw"
file_id     = "${proxmox_virtual_environment_file.debian_12_genericcloud.datastore_id}:${proxmox_virtual_environment_file.debian_12_genericcloud.content_type}/${proxmox_virtual_environment_file.debian_12_genericcloud.file_name}"
interface = "virtio0"
size      = 10
}
```
to
```terraform
disk {
datastore_id = var.vm_datastore
file_format = "raw"
file_id     = "${proxmox_virtual_environment_file.debian_12_genericcloud.datastore_id}:${proxmox_virtual_environment …
```
=> fix(vm): set FileVolume for disks with file_id

fwprovider/tests/resource_file_test.go, proxmoxtf/resource/file.go
- `terraform apply` this plan:
```terraform
resource "proxmox_virtual_environment_file" "test_file" {
content_type = "snippets"
node_name    = "pve"
source_file {
path = "https://raw.githubusercontent.com/yaml/yaml-test-suite/main/src/229Q.yaml"
}
}
```
- delete file `229Q.yaml` from `snippets`
- run `terraform apply` again
Before the fix:
```
proxmox_virtual_environment_file.test_file: Refreshing state... [id=local:snippets/229Q.yaml]
╷
│ Error: no such file: "local:snippets/229Q.yaml"
│ 
│   with proxmox_virtual_environment_file.test_file,
│   on main.tf line 31, in resource "proxmox_virtual_environment_file" "test_file":
│   31: resource "proxmox_virtual_environment_file" "test_file" {
│ 
╵
```
After the fix:
```
proxmox_virtual_environment_file.test_file: …
```
=> fix(file): handle missing file on state refresh

proxmoxtf/resource/validator/network.go, proxmoxtf/resource/validator/network_test.go
=> fix(vm): MAC address validator should allow lowercase hex

docs/resources/virtual_environment_vm.md
Modify example to start with disabled guest agent.
#669 and #449 show that `agent.enabled = true` behavior is not obvious and should be documented. It should not be the default in the example, but users are still expected to change it to true once they understand the details and configure everything correctly.
Closes #669 | Relates #0000
=> fix(docs): document qemu-guest-agent behavior

docs/index.md, proxmox/api/client.go
Ignore `/api2/json` path in case it is present in the endpoint.
Closes #547
=> fix(provider): sanitize PVE endpoint value

proxmoxtf/resource/vm.go
PR #694 has introduced a datatype change `int` -> `int64` for [memory values](https://github.com/bpg/terraform-provider-proxmox/pull/694/files#diff-2f1b4764b499dad0e71c1d1ec4643ab8ecb1b91e24e00c6e4bbe3ecd9c242a89L436) in `GetResponseData` struct, which is used when provider reads VM state from PVE. However, `int64` does not play well with the SDK type `schema.TypeInt` used by the schema attributes, causing `null` values on read.
Create a minimal VM template, apply. Then call `terraform apply` again.
Before the fix:
After the fix:
* Please do not …
=> fix(vm): memory size datatype conversion causing `null` on read

proxmox/api/client.go
to use, set the https_proxy environment variable before running terraform
for example:
export https_proxy=http://localhost:8080
this will easy troubleshooting the plugin
for example, this is how it looks in [mitmproxy](https://mitmproxy.org):
=> feat(provider): modify the proxmox api client to support connecting through an https proxy

proxmoxtf/resource/validator/file.go, proxmoxtf/resource/validator/file_test.go
=> fix(vm,lxc): file ID validator to allow `.` in a storage name

proxmoxtf/resource/vm.go
Re-work order of when we resize image. First import disk and then resize. This was resize should be quicker
See #737
=> fix(vm): resize image once imported 

proxmoxtf/resource/container.go
Tested with description in different formats:
```
description = "some desc"
```
```
description = <<-EOT
some
desc
EOT
```
```
description = <<-EOT
some desc
EOT
```
No changes detected after the first apply.
Closes #721
=> fix(lxc): description is always showed as changed

docs/resources/virtual_environment_vm.md, example/resource_virtual_environment_vm.tf, proxmox/nodes/vms/vms_types.go, proxmoxtf/resource/vm.go
Add support for setting the VM TPM State hardware.
Please feel free to squash all the commits.
The TPM State hardware can be declared as:
```hcl
resource "proxmox_virtual_environment_vm" "example" {
tpm_state {
version      = "v2.0"
}
...
}
```
I've partially executed the example (see error after the screenshot). Here's the screenshot of the example created VM that shows it with the TPM State device:
Here's the error (which seems not related to this PR):
```
╷
│ Error: error updating container: received an HTTP 400 response - Reason: Parameter verification failed. (mp0: unable to hotplug mp0: directory '/mnt/bindmounts/shared' does not exist)
│ 
│   with proxmox_virtual_environment_container.example,
│   on resource_virtual_environment_container.tf line 52, in …
```
=> feat(vm): Add support for setting the VM TPM State device

proxmox/nodes/vms/vms_types.go, proxmox/nodes/vms/vms_types_test.go, proxmoxtf/resource/vm.go
This configuration now works after the fix
```hcl
interface    = "scsi2"
ip_config {
ipv4 {
address = "dhcp"
}
}
}
```
```
...
+ initialization {
+ datastore_id      = "local"
+ interface         = "scsi2"
+ user_data_file_id = (known after apply)
+ ip_config {
+ ipv4 {
+ address = "dhcp"
}
}
}
+ memory {
+ dedicated = 2048
+ floating  = 0
+ shared    = 0
}
+ network_device {
+ bridge      = "vmbr0"
+ enabled     = true
+ firewall    = false
+ mac_address = (known after apply)
+ model       = "virtio"
+ mtu         = 0
+ queues      = 0
+ rate_limit  = 0
+ vlan_id     = 0
}
+ operating_system {
+ type = "l26"
}
}
Plan: 3 to add, 0 to change, 0 to destroy.
proxmox_virtual_environment_file.ubuntu_cloud_image: Creating... …
```
=> fix(vm): panic at read when cloud-init drive is on directory storage

docs/index.md, proxmoxtf/provider/schema.go
It is now possible to use an FQDN instead of an IP Address when the SSH node is configured
```hcl
variable "pm_nodes" {
type = list(object({
name    = string
address = string
port    = number
}))
}
provider "proxmox" {
endpoint = "https://${var.pm_host}:${var.pm_webport}/"
username = "${var.pm_user}@pam"
password = var.pm_password
insecure = true
tmp_dir  = "${path.module}"
ssh {
agent = true
dynamic "node" {
for_each = var.pm_nodes
content {
name    = node.value.name
address = node.value.address
port    = node.value.port
}
}
}
}
```
in the example, the node address variable can be also an FQDN instead of an IP address.
- Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull …
=> fix(provider): allow FQDN for `ssh.node.address` in provider's config

docs/resources/virtual_environment_container.md, docs/resources/virtual_environment_vm.md, example/resource_virtual_environment_container.tf, example/resource_virtual_environment_vm.tf, proxmoxtf/resource/container.go, proxmoxtf/resource/container_test.go, proxmoxtf/resource/vm.go, proxmoxtf/resource/vm_test.go
Added `servers` param, deprecate old `server` param. Apply AFAIK works as expected, tried some of combinations:
- old server and no servers
- both server and servers
- new servers without server
- old server and no servers -> apply -> then only servers
Closes https://github.com/bpg/terraform-provider-proxmox/issues/816
=> feat(vm, lxc): add new `initialization.dns.servers` param to vm and container

proxmoxtf/resource/vm.go
Having this VM in PVE:
Import:
```
❯ terraform import proxmox_virtual_environment_vm.test pve/1000
proxmox_virtual_environment_vm.test: Importing from ID "pve/1000"...
proxmox_virtual_environment_vm.test: Import prepared!
Prepared proxmox_virtual_environment_vm for import
proxmox_virtual_environment_vm.test: Refreshing state... [id=1000]
Import successful!
The resources that were imported are shown above. These resources are now in
your Terraform state and will henceforth be managed by Terraform.
```
Check the state:
```
❯ terraform state show proxmox_virtual_environment_vm.test
resource "proxmox_virtual_environment_vm" "test" {
acpi                    = true
bios                    = "seabios"
id                      = "1000"
ipv4_addresses          = [
[
"127.0.0.1",
],
[ …
```
=> fix(vm): missing disks when importing VM to a TF state

.github/workflows/golangci-lint.yml, .github/workflows/metrics.yml, .github/workflows/publish.yml, .github/workflows/release-please.yml, .github/workflows/semgrep.yml, .github/workflows/stale.yaml, .github/workflows/test.yml
=> chore(ci): update

proxmoxtf/resource/pool.go
With template:
```terraform
resource "proxmox_virtual_environment_pool" "import" {
pool_id = "test"
}
```
```
❯ terraform import proxmox_virtual_environment_pool.import test
proxmox_virtual_environment_pool.import: Importing from ID "test"...
proxmox_virtual_environment_pool.import: Import prepared!
Prepared proxmox_virtual_environment_pool for import
proxmox_virtual_environment_pool.import: Refreshing state... [id=test]
Import successful!
The resources that were imported are shown above. These resources are now in
your Terraform state and will henceforth be managed by Terraform.
❯ terraform plan
proxmox_virtual_environment_pool.import: Refreshing state... [id=test]
No changes. Your infrastructure matches the configuration.
Terraform has compared your real infrastructure against your …
```
=> fix(pool): missing `pool_id` after import

proxmoxtf/resource/container.go
Apply & reapply a template with
```terraform
ip_config {}
}
```
```
Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
~ update in-place
Terraform will perform the following actions:
~ resource "proxmox_virtual_environment_container" "test_container" {
id            = "102"
tags          = []
~ initialization {
+ ip_config {
}
}
}
Plan: 0 to add, 1 to change, 0 to destroy.
proxmox_virtual_environment_container.test_container: Modifying... [id=102]
proxmox_virtual_environment_container.test_container: Modifications complete after 0s [id=102]
Apply complete! Resources: 0 added, 1 changed, 0 destroyed.
```
- Please vote on this pull request by adding a 👍 …
=> fix(lxc): panic on empty `initialization.ip_config` block

proxmox/nodes/vms/vms.go, proxmox/nodes/vms/vms_types.go
Logs 
- before:
`2024-01-27T21:37:50.202-0500 [DEBUG] provider.terraform-provider-proxmox: Sending HTTP Request: @caller=<REDACTED>/terraform-plugin-sdk/v2@v2.31.0/helper/logging/logging_http_transport.go:162 Csrfpreventiontoken=65B5BDDA:ffi7fjzOUpqdvxZwZxHTQAi7o3qmTEEzkR+vrDlx/+0 tf_http_req_uri=/api2/json/nodes/pve/qemu/1000/status/start tf_http_req_method=POST tf_http_req_version=HTTP/1.1 tf_mux_provider=tf5to6server.v5tov6Server Accept=application/json Content-Length=0 User-Agent=Go-http-client/1.1 tf_rpc=ApplyResourceChange Cookie=PVEAuthCookie=<REDACTED> tf_http_op_type=request tf_provider_addr=registry.terraform.io/bpg/proxmox tf_req_id=dd0a08f5-96a6-bebe-9783-1af7f42e672f tf_resource_type=proxmox_virtual_environment_vm @module=proxmox Accept-Encoding=gzip Host=pve.boldyrev.me:8006 …
=> fix(vm): `timeout_start_vm` is ignored

.vscode/settings.json, docs/index.md, proxmoxtf/resource/file.go, proxmoxtf/resource/sudo.go, proxmoxtf/resource/vm.go
With sudoers like
```
terraform ALL=(root) NOPASSWD: /sbin/pvesm
terraform ALL=(root) NOPASSWD: /sbin/qm
terraform ALL=(root) NOPASSWD: /usr/bin/mv /tmp/tfpve/* /var/lib/vz/*
```
and permissions on the datastore folder
```
root@pve:~# ls -la /var/lib/vz/
total 28
drwxr-xr-x  7 root root 4096 Dec 17 18:05 .
drwxr-xr-x 38 root root 4096 Jan 26 20:06 ..
drwxr-xr-x  2 root root 4096 Nov  5 09:32 dump
drwxr-xr-x  3 root root 4096 Feb  3 23:33 images
drwxr-xr-x  2 root root 4096 Dec 17 18:05 private
drwxr-xr-x  2 root root 4096 Feb  5 00:20 snippets
drwxr-xr-x  4 root root 4096 Feb  5 00:13 template
```
applying of the [example template](https://github.com/bpg/terraform-provider-proxmox/blob/main/examples/guides/cloud-init/custom/main.tf) works without errors:
```
Plan: 3 to add, 0 to change, 0 …
```
=> fix(file): use `sudo` for snippets upload

proxmoxtf/resource/vm.go
A VM template with initialization block like
```terraform
user_account {
}
}
```
now can be successfully applied:
```
...
+ initialization {
+ datastore_id = "local-lvm"
+ user_account {}
}
}
Plan: 1 to add, 0 to change, 0 to destroy.
proxmox_virtual_environment_vm.centos_vm: Creating...
proxmox_virtual_environment_vm.centos_vm: Still creating... [10s elapsed]
proxmox_virtual_environment_vm.centos_vm: Still creating... [20s elapsed]
proxmox_virtual_environment_vm.centos_vm: Creation complete after 24s [id=102]
Apply complete! Resources: 1 added, 0 changed, 0 destroyed.
```
- Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the …
=> fix(vm): fix panic when a config block is empty

.vscode/settings.json, proxmoxtf/resource/container.go
Besides the panic from #1025, also fixes setting the `firewall` flag on container's network interface at creation.
Apply & re-apply of the following plan works now:
```terraform
resource "proxmox_virtual_environment_container" "test_container" {
node_name = var.virtual_environment_node_name
vm_id     = 9000
disk {
size         = 8
}
started  = false
template = true
hostname = "test"
ip_config {
ipv4 {
address = "dhcp"
}
}
user_account {
password = "password"
}
}
network_interface {
name     = "vmbr0"
firewall = true
}
operating_system {
template_file_id = proxmox_virtual_environment_download_file.ubuntu_container_template.id
type             = "ubuntu"
}
}
resource "proxmox_virtual_environment_download_file" "ubuntu_container_template" { …
```
=> fix(lxc): panic when handling `network_interface.firewall` attribute

proxmoxtf/resource/container.go
Apply & re-apply of this template works without panic now:
```terraform
resource "proxmox_virtual_environment_container" "test_container" {
node_name = var.virtual_environment_node_name
disk {
size         = 8
}
started  = true
hostname = "test"
ip_config {
ipv4 {}
ipv6 {}
}
user_account {
password = "password"
}
}
network_interface {
name     = "vmbr0"
firewall = true
}
operating_system {
template_file_id = proxmox_virtual_environment_download_file.ubuntu_container_template.id
type             = "ubuntu"
}
}
resource "proxmox_virtual_environment_download_file" "ubuntu_container_template" {
content_type = "vztmpl"
node_name    = "pve"
url          = "http://download.proxmox.com/images/system/ubuntu-20.04-standard_20.04-1_am …
```
=> fix(lxc): panic on empty `initialization.ip_config.ipv4|6` block

.vscode/launch.json, fwprovider/tests/resource_vm_test.go, proxmoxtf/resource/container/container.go, proxmoxtf/resource/vm/vm.go
Using the [cloud-init example](https://github.com/bpg/terraform-provider-proxmox/blob/main/examples/guides/cloud-init/custom/main.tf) with addition of these outputs:
```terrafrom
output "vm_all_ipv4_address" {
value = proxmox_virtual_environment_vm.ubuntu_vm.ipv4_addresses
}
output "vm_all_mac_addresses" {
value = proxmox_virtual_environment_vm.ubuntu_vm.mac_addresses
}
```
Results before the fix:
```
Outputs:
vm_all_ipv4_address = tolist([
tolist([
"127.0.0.1",
]),
tolist([
"192.168.XXX.XXX",
]),
])
vm_all_mac_addresses = tolist([
"BC:24:11:17:49:4F",
])
```
after the fix:
```
Outputs:
vm_all_ipv4_address = tolist([
tolist([
"127.0.0.1",
]),
tolist([
"192.168.XXX.XXX",
]),
])
vm_all_mac_addresses = tolist([
"00:00:00:00:00:00",
"BC:24:11:6B:F9:89",
])
```
- Please vote on this pull …
=> fix(vm): regression: `mac_addresses` list is missing some interfaces

proxmox/ssh/client.go
I am using the provider and repeatedly ran into an issue where the .ssh directory was already existent for some users, when the provider tried to add authorized_keys. This small change should fix this issue.
The screenshot below shows the error that kept popping up for me.
With the small fix in this PR if have not encountered the issue again.
An alternative way could be to use [os.mkdirall](https://pkg.go.dev/os#MkdirAll) but I figured this way introduces the least changes.
- Please do not leave "+1" or other comments that do not add relevant new …
=> fix(provider): race condition in`~/.ssh` path existence check

.github/workflows/test.yml, .github/workflows/testacc.yml, docs/index.md, example/main.tf, example/variables.tf, fwprovider/tests/resource_file_test.go, proxmox/ssh/client.go, proxmoxtf/resource/file.go
[Acceptance tests pass on CI](https://github.com/bpg/terraform-provider-proxmox/actions/runs/8126164548/job/22209538897)
Closes #1008
Closes #1070
=> feat(file)!: snippets upload using SSH input stream

docs/resources/virtual_environment_container.md, docs/resources/virtual_environment_vm.md
Simple fix for the docs to match the updated define
=> fix(docs): fix wrong startup delay attributes

docs/resources/virtual_environment_vm.md, fwprovider/tests/resource_vm_test.go, proxmox/nodes/vms/vms_types.go, proxmoxtf/resource/vm/network/network.go, proxmoxtf/resource/vm/network/schema.go
A VM template with
```terraform
network_device {
bridge = "vmbr0"
disconnected = true
}
```
produced:
Closes #1093
=> feat(vm): add support for `disconnected` attribute in network interface

example/resource_virtual_environment_vm.tf
otherwise it defaults to dvInitializationDatastoreID
=> fix(examples): `datastore_id` is missing in `initialization` block for vm 

docs/resources/virtual_environment_container.md, proxmoxtf/resource/container/container.go
I might have pretty fast disks, so wasn't able to reproduce the exact issue from #1107.
But the argument form template is getting passed down to the container create call.
Closes #1107
=> feat(lxc): add configurable timeout for container creation

docs/resources/virtual_environment_vm.md, example/resource_virtual_environment_vm.tf, proxmox/nodes/vms/vms_types.go, proxmoxtf/resource/vm/validators.go, proxmoxtf/resource/vm/vm.go
It helps to pin VMs to the special cpu.
```terraform
cpu {
cores = 2
affinity = "2,3"
}
```
Closes #1148
=> feat(vm): add support for cpu `affinity` attribute (#1148)

docs/resources/virtual_environment_container.md, proxmoxtf/resource/container/container.go
>Because of the environment type I work on, it is not possible for me to use the `make example` test command. But I tested directly with a real resource as you will see bellow.
Basically, this PR add a very simple fix about a previous one. The changes are about:
- Fix timeouts on CT creation
- Add configurable timeout for CT start
**Before**
```bash
proxmox_virtual_environment_container.homarr: Creating...
proxmox_virtual_environment_container.homarr: Still creating... [10s elapsed]
proxmox_virtual_environment_container.homarr: Still creating... [20s elapsed]
proxmox_virtual_environment_container.homarr: Still creating... [30s elapsed]
proxmox_virtual_environment_container.homarr: Still creating... [40s elapsed]
proxmox_virtual_environment_container.homarr: Still creating... [50s elapsed] …
```
=> fix(lxc): improve configurable timeouts for containers operations

proxmox/api/ticket_auth.go
Upstreaming some additions/fixes from my fork.
I don't remember why this was an issue, as I added this almost a year ago, but it was breaking something.
=> fix: prevent authenticating multiple times in parallel

fwprovider/tests/resource_vm_test.go, proxmoxtf/resource/vm/vm.go, testacc
The new test fails before the fix:
```
=== NAME  TestAccResourceVM/update_memory_block
resource_vm_test.go:174: Step 2/2 error: Error running apply: exit status 1
Error: error updating VM: received an HTTP 500 response - Reason: only root can set 'hugepages' config
with proxmox_virtual_environment_vm.test_vm6,
on terraform_plugin_test.tf line 12, in resource "proxmox_virtual_environment_vm" "test_vm6":
12:                           resource "proxmox_virtual_environment_vm" "test_vm6" {
--- FAIL: TestAccResourceVM (0.00s)
--- FAIL: TestAccResourceVM/update_memory_block (4.72s)
```
After the fix:
```
--- PASS: TestAccResourceVM (0.00s)
--- PASS: TestAccResourceVM/update_memory_block (5.49s)
PASS
```
- Please vote on this pull request by adding a 👍 …
=> fix(vm): regression: provider always tries to update `memory.*hugepages` even if it is not specified

utils/maps.go, utils/maps_test.go
Updated unit test before the fix:
```
go test -timeout 30s -run ^TestMapResourceList$ github.com/bpg/terraform-provider-proxmox/utils
--- FAIL: TestMapResourceList (0.00s)
panic: interface conversion: interface {} is nil, not map[string]interface {} [recovered]
panic: interface conversion: interface {} is nil, not map[string]interface {}
goroutine 21 [running]:
testing.tRunner.func1.2({0x100fee0c0, 0x140000af200})
/opt/homebrew/Cellar/go/1.22.2/libexec/src/testing/testing.go:1631 +0x1c4
testing.tRunner.func1()
/opt/homebrew/Cellar/go/1.22.2/libexec/src/testing/testing.go:1634 +0x33c
panic({0x100fee0c0?, 0x140000af200?})
/opt/homebrew/Cellar/go/1.22.2/libexec/src/runtime/panic.go:770 +0x124
github.com/bpg/terraform-provider-proxmox/utils.MapResourceList(...) …
```
=> fix(vm): panic if `numa` block is empty

fwprovider/tests/resource_firewall_test.go, proxmoxtf/resource/firewall/rules.go
A cluster-level rule like
```terraform
resource "proxmox_virtual_environment_firewall_rules" "rules1" {
rule {
type   = "in"
action = "ACCEPT"
iface  = "vmbr0"
dport = "8006"
proto = "tcp"
comment = "PVE Admin Interface"
}
}
```
now can be created without errors. New acceptance test passes:
```
--- PASS: TestAccResourceClusterFirewall (0.00s)
--- PASS: TestAccResourceClusterFirewall/rules1 (1.17s)
PASS
ok      github.com/bpg/terraform-provider-proxmox/fwprovider/tests      1.432s
```
- Please do not leave "+1" or other comments that do not add …
=> fix(firewall): remove strict validation for `rule.iface` attribute

example/resource_virtual_environment_vm.tf, proxmoxtf/resource/vm/vm.go
Hello,
There seems to be an issue with how EFI disks types are compared. I stumbled upon it while cloning a template which was created using packer. The type was the same for both packer and terraform, but it was failing with the following log:
```
Error: resizing of efidisks is not supported.
```
After switching to comparing the values, it creates the VM as intended. I did not test it with `make example`, but tried it on my local test cluster: I'll try to run the example when I have the chance.
Kind regards,
Joris
Updated example template fails without fix:
```
proxmox_virtual_environment_firewall_options.container_options: Creating...
proxmox_virtual_environment_firewall_ipset.container_ipset: Creating...
proxmox_virtual_environment_firewall_rules.container_rules: Creating... …
```
=> fix(vm): error 'resizing of efidisks is not supported' when clonning a VM with re-defined `efi_disk`

fwprovider/tests/resource_hardware_mapping_test.go
Fix the [failing acceptance test](https://github.com/bpg/terraform-provider-proxmox/actions/runs/8743959587/job/23995760040#step:7:175) for the new hardware mapping functionality (#1213)
=> chore(vm): fix acceptance test for hardware mapping

docs/resources/virtual_environment_cluster_options.md, examples/resources/proxmox_virtual_environment_cluster_options/resource.tf, fwprovider/resource_options.go, fwprovider/tests/resource_options_test.go, proxmox/cluster/options_types.go
This pull request implements the `next-id` and `notify` [PVE API cluster options](https://pve.proxmox.com/pve-docs/api-viewer/#/cluster/options).
The `next-id` attribute allows to control the range for the next free VM ID. It is implemented as object and can be used in the `proxmox_virtual_environment_cluster_options` resource like this:
```terraform
resource "proxmox_virtual_environment_cluster_options" "options" {
next_id = {
lower = 200
upper = 299
}
}
```
Note that **the minimum and maximum values are unfortunately not documented in the PVE API explorer** but can be found in the web UI where the form fields have validations!
The `notify` PVE API attribute is also an object that has all the PVE API fields:
```terraform
resource "proxmox_virtual_environment_cluster_options" "options" { …
```
=> feat(cluster): Extend the available attributes for the `proxmox_virtual_environment_cluster_options` resource

docs/resources/virtual_environment_vm.md, fwprovider/tests/resource_vm_test.go, proxmoxtf/resource/vm/vm.go
This template can be applied without errors:
```hcl
resource "proxmox_virtual_environment_vm" "test_efi_disk" {
name 	  = "test-efi-disk"
efi_disk {
type = "4m"
}
}
```
Closes #1246
=> fix: use `raw` file format for `efi_disk` by default

docs/index.md, go.mod, go.sum, proxmox/ssh/client.go, proxmox/ssh/client_notwindows.go, proxmox/ssh/client_windows.go, proxmoxtf/provider/provider.go
=> feat(provider): add support for `ssh-agent` on Windows

fwprovider/tests/resource_vm_test.go, proxmoxtf/resource/vm/vm.go
Regression after #1237
```hcl
resource "proxmox_virtual_environment_vm" "test_cdrom" {
name      = "test-cdrom"
cdrom {
enabled = true
}
}
```
```
OpenTofu used the selected providers to generate the following execution plan. Resource actions are indicated
with the following symbols:
+ create
+ resource "proxmox_virtual_environment_vm" "test_cdrom" {
+ acpi                    = true
+ bios                    = "seabios"
+ id                      = (known after apply)
+ ipv4_addresses          = (known after apply)
+ ipv6_addresses          = (known after apply)
+ keyboard_layout         = "en-us"
+ mac_addresses           = (known after apply)
+ migrate                 = false
+ name                    = …
```
=> fix(vm): `cdrom` is not attached when creating a VM from scratch

README.md, fwprovider/access/resource_user_token.go, fwprovider/tests/resource_user_test.go
…:00Z" if undefined
Closes #1292
=> fix(access): user token `expiration_date` handling

proxmox/nodes/tasks/tasks.go
Follow up for #1317 . After testing it, I noticed that the provider still failed. I logged down the values, it appears that warnings is set to the ExitCode parameter instead.
`status.Status=stopped`
`status.ExitCode=WARNINGS: 1`
After this patch, when VM has warning status, state is retained in provider and VM is successfully started.
Relates #1314
=> fix(vm): check task warning status against exit code

.github/workflows/testacc.yml, fwprovider/test/resource_container_test.go, fwprovider/test/resource_vm_test.go, fwprovider/test/test_environment.go, proxmoxtf/resource/vm/disk/disk.go, proxmoxtf/resource/vm/disk/schema.go, proxmoxtf/resource/vm/vm.go
Another attempt to fix #103. 
May not work for all use cases though. Still need to be tested better for cloning, hotplug update, adding multiple disks, mixed disk updates, datastore migrations etc.
First, apply this template:
```hcl
resource "proxmox_virtual_environment_vm" "test_disk" {
name      = "test-disk"
disk {
file_format  = "raw"
interface    = "virtio0"
size         = 8
}
}
```
```
+ create
+ resource "proxmox_virtual_environment_vm" "test_disk" {
+ acpi                    = true
+ bios                    = "seabios"
+ id …
```
=> fix(vm): adding disks causes VM to be re-created

docs/resources/virtual_environment_vm.md, example/resource_virtual_environment_vm.tf, fwprovider/test/resource_vm_disks_test.go, proxmox/nodes/vms/custom_storage_device.go, proxmoxtf/resource/vm/disk/disk.go, proxmoxtf/resource/vm/disk/schema.go
```hcl
resource "proxmox_virtual_environment_vm" "test_disk" {
name 	    = "test-disk"
disk {
file_format  = "raw"
interface    = "virtio0"
serial	 = "dead_beef"
size         = 8
replicate    = false
aio          = "native"
}
}
```
```
+ create
+ resource "proxmox_virtual_environment_vm" "test_disk" {
+ acpi                    = true
+ bios                    = "seabios"
+ id                      = (known after apply)
+ ipv4_addresses          = (known after apply)
+ ipv6_addresses          = (known after apply)
+ keyboard_layout         = "en-us" …
```
=> feat(vm): add support for `disk.serial` attribute 

example/resource_virtual_environment_container.tf, fwprovider/test/resource_container_test.go, proxmoxtf/resource/container/container.go
=> fix(lxc): use default rootfs size (4Gb) prevents creation of mount points

docs/resources/virtual_environment_container.md
Volid's can be used with `template_file_id`.
Just a small doco tweak.
=> fix(docs): Mention alternate valid use of Volid's for containers

.github/workflows/code-quality.yml, docs/data-sources/virtual_environment_vm.md, docs/data-sources/virtual_environment_vms.md, example/data_source_virtual_environment_vms.tf, proxmox/nodes/vms/vms_types.go, proxmoxtf/datasource/vm.go, proxmoxtf/datasource/vm_test.go, proxmoxtf/datasource/vms.go, proxmoxtf/datasource/vms_test.go
* Additional attributes for vm data source (status, template)
Relates #1010
=> feat(vm): implement filtering in vms data source.

proxmox/nodes/vms/custom_usb_device.go, proxmox/nodes/vms/custom_usb_device_test.go
Added a new unit test for this specific cases, which passes after the fix.
Closes #1342
=> fix(vm): panic when reading VM with SPICE USB passthrough

docs/index.md, docs/resources/virtual_environment_download_file.md, templates/resources/virtual_environment_download_file.md.tmpl
=> fix(docs): document role privileges required by `proxmox_virtual_environment_download_file`

proxmox/nodes/storage/upload.go
Good Day!
This PR contains a change to `proxmox/nodes/storage/upload.go`, in the deferred call to `fileReader.Close()`. This adds a branch to check if the error returned from the Close call is an `os.ErrClosed`, and if so ignores the error.
This resolves an issue I am having while using the downstream [pulumi-proxmoxve](https://github.com/muhlba91/pulumi-proxmoxve) provider which is based on this terraform provider. In my use case, I am using NixOS, and am trying to create an LXC container based on a vztmpl which is generated locally on my workstation and being uploaded to Proxmox via the pulumi equivalent to the `proxmox_virtual_environment_file` resource.
The error I am having is that whenever the `nixos-system-x86_64-linux.tar.xz` file (size of approximately 114Mb) is uploaded to the …
=> fix(storage): ignore `os.ErrClosed` from deferred `fileReader.Close()` in storage.APIUpload

docs/resources/virtual_environment_container.md, docs/resources/virtual_environment_file.md, docs/resources/virtual_environment_vm.md, example/resource_virtual_environment_file.tf, proxmox/api/client_types.go, proxmox/ssh/client.go, proxmoxtf/resource/file.go, proxmoxtf/resource/file_test.go, proxmoxtf/resource/validators/file.go, proxmoxtf/resource/validators/file_test.go
#733 implemented basic support for hook scripts, but [the authors "did not manage to find time to work on"][1] also including support to set the file mode. This small but important feature makes the use of the [`proxmox_virtual_environment_container.hook_script_file_id`][2] and [`virtual_environment_vm.hook_script_file_id`][3] attributes basically useless when not combined with the manual step of making the uploaded file executable (manually running `chmod +x /path/to/script` or using other methods, based on the storage backend). Using the `hook_script_file_id` on its own also causes all planned and applied changes in the same execution to not be saved in the state because the Proxmox VE API responses with a HTTP `500` error since the uploaded and assigned file is not executable.
This …
=> feat(file): add support to set the file mode

example/resource_virtual_environment_container.tf, example/resource_virtual_environment_download_file.tf, example/variables.tf
=> chore(example): update links to container images, use faster mirror

proxmoxtf/resource/vm/validators.go, proxmoxtf/resource/vm/vm.go
With this template
```hcl
resource "proxmox_virtual_environment_vm" "test_cdrom" {
vm_id     = 999
name      = "test-cpu-arch"
cpu {
cores = 2
sockets = 1
}
}
```
Before the fix:
```
❯ tofu apply -auto-approve
+ create
+ resource "proxmox_virtual_environment_vm" "test_cdrom" {
+ acpi                    = true
+ bios                    = "seabios"
+ id                      = (known after apply)
+ ipv4_addresses          = (known after apply)
+ ipv6_addresses          = (known after apply)
+ keyboard_layout         = "en-us"
+ mac_addresses           = (known after apply)
+ …
```
=> fix(vm): `cpu.architecture` showed as new attribute at re-apply after creation

docs/resources/virtual_environment_vm.md, fwprovider/vm/cdrom/resource.go, proxmox/nodes/vms/custom_pci_device.go, proxmox/nodes/vms/vms_types.go, proxmox/nodes/vms/vms_types_test.go, proxmoxtf/resource/vm/disk/disk.go, proxmoxtf/resource/vm/vm.go
Using template:
```hcl
resource "proxmox_virtual_environment_vm" "test_vm" {
vm_id     = 999
name      = "test-hostpci"
started = false
hostpci {
device = "hostpci0"
id     = "0000:01:00.0"
pcie   = true
}
hostpci {
device = "hostpci2"
id     = "0000:01:00.0"
pcie   = true
}
hostpci {
device = "hostpci4"
id     = "0000:01:00.0"
pcie   = true
}
hostpci {
device = "hostpci6"
id     = "0000:01:00.0"
pcie   = true
}
hostpci {
device = "hostpci8"
id     = "0000:01:00.0"
pcie   = true
}
}
```
Before the fix:
```
+ create
+ resource "proxmox_virtual_environment_vm" "test_vm" {
+ acpi …
```
=> fix(vm): handle more than 4 `hostpci` devices

docs/resources/virtual_environment_container.md, proxmoxtf/resource/container/validators.go
=> chore(lxc): update list of supported OS-es in `operating_system.type`

fwprovider/test/resource_container_test.go, proxmoxtf/resource/container/container.go
Update existing acceptance test to check this use case.
The fast fails before the fix:
```
=== RUN   TestAccResourceContainer/update_mount_points
=== PAUSE TestAccResourceContainer/update_mount_points
=== CONT  TestAccResourceContainer/update_mount_points
resource_container_test.go:253: Step 2/2 error: Error running apply: exit status 1
Error: error updating container: received an HTTP 500 response - Reason: unable to parse volume ID 'local-lvm'
with proxmox_virtual_environment_container.test_container,
on terraform_plugin_test.tf line 22, in resource "proxmox_virtual_environment_container" "test_container":
22: 				resource "proxmox_virtual_environment_container" "test_container" {
--- FAIL: TestAccResourceContainer/update_mount_points (8.92s)
```
producing these PUT request params: …
=> fix(lxc): add new storage-backed mount point to existing container

proxmox/ssh/client.go
~I have **not** tested this but~ it's pretty simple and I think it should work fine.
Should fix this error:
```
Error: creating custom disk: unable to authenticate user "root" over SSH to "fdaa:a:a:a:2::3:22". Please verify that ssh-agent is correctly loaded with an authorized key via 'ssh-add -L' (NOTE: configurations in ~/.ssh/config are not considered
infrastructure  by the provider): failed to dial fdaa:a:a:a:2::3:22: dial tcp: address fdaa:a:a:a:2::3:22: too many colons in address
```
=> fix(provider): handle IPv6 in ssh client

docs/resources/virtual_environment_container.md
#837 Changed the example container template url from: 
`http://download.proxmox.com/images/system/ubuntu-20.04-standard_20.04-1_amd64.tar.gz` 
to: 
`https://cloud-images.ubuntu.com/jammy/current/jammy-server-cloudimg-amd64.tar.gz`. 
The latter is a `QCOW v2` image, so following the example as it's currently written will create a container that doesn't start: `__lxc_start: 2114 Failed to spawn container "1234"`.
This PR just undoes this change in the docs so that following the example for the `proxmox_virtual_environment_container` resource works as expected.
- Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize …
=> fix(docs): correct url for template download in container resource example

proxmox/helpers/ptr/ptr.go, proxmoxtf/resource/vm/disk/disk.go, proxmoxtf/resource/vm/vm.go
After the fix, the disk can be increased without restart:
```
~ update in-place
~ resource "proxmox_virtual_environment_vm" "ubuntu_vm" {
id                      = "24044"
name                    = "test-ubuntu"
tags                    = []
~ disk {
~ size              = 42 -> 45
}
}
Plan: 0 to add, 1 to change, 0 to destroy.
proxmox_virtual_environment_vm.ubuntu_vm: Modifying... [id=24044]
proxmox_virtual_environment_vm.ubuntu_vm: Modifications complete after 1s [id=24044]
Apply complete! Resources: 0 added, 1 changed, 0 destroyed.
```
No restart in the task log:
Also, disk shrinking is properly reported as …
=> fix(vm): do not reboot at disk resize

Makefile, example/test-api-creds-auth/.gitignore, example/test-api-creds-auth/api-creds-tester.sh, example/test-api-creds-auth/data_object.tf, example/test-api-creds-auth/main.tf, example/test-api-creds-auth/variables.tf, example/test-api-creds-auth/versions.tf
Here's the monster shell looper to test api combination paths ( script self-creates a shell-config-file that would need to be updated for success-expected tests )
- hardest part is/was the labeling of things; understood if decided to not merge it
- proof of work area is a subsection; a chuck of the expected-failure tests are a bit overkill, and the otp via provider is failing but in the 'success' area (now im 2nd guessing where i should've placed that lol)
- i did not add in thorough dependency checks (like python's pyotp, jq, ect) 
- does not fork (does one test at a time)
- fake-tests using real usernames which have totp will get the totp locked; solution was to run the api to unlock a users totp before every call (kind of funky imo but did the trick)
example output (of `make …
=> chore(tests): add script to test/view api-authentication successes/failures

proxmoxtf/resource/vm/vm.go
Regression after #1580, the provider incorrectly detects that disk has been resized when other disk attributes change.
Actually, the existing acceptance tests were failing, but that went unnoticed 😞 
=> fix(vm): incorrect detection of disk resize

docs/resources/virtual_environment_container.md, proxmoxtf/resource/container/container.go
The proxmox pct command allows for `disk size = 0`  to create containers backed by ZFS or BTRFS subvolumes. (Note that this is still not allowed by the GUI.) This would allow the provider to use this feature as well.
https://pve.proxmox.com/pve-docs/pct.1.html
Storage Backed Mount Points
Directories: passing size=0 triggers a special case where instead of a raw image a directory is created.
```
resource "proxmox_virtual_environment_container" "k3s-controller" {
id             = "134"
node_name      = "pve-host"
protection     = false
start_on_boot  = true
started        = true
tags           = [
"k3s-controller",
]
template       = false
timeout_clone  = 1800
timeout_create = 1800
timeout_delete = 60
timeout_start  = 300
timeout_update = 1800
unprivileged   = false
vm_id          = 134 …
```
=> fix(lxc): allow container disk size 0 for lxc zfs/brfs subvols

docs/resources/virtual_environment_file.md, proxmoxtf/resource/file.go, proxmoxtf/resource/validators/file.go
Updated the validation file.go file as mentioned by @bpg at the relevant issue. Additionally, needed to update the contentType FileUploadRequest to keep it from using backup. Proxmox expects backups to be located at the "dump" directory
```hcl
resource "proxmox_virtual_environment_file" "fetch_debian_lxc_template" {
content_type = "backup"
node_name    = "pve"
overwrite    = true
source_file {
path      = "vzdump-lxc-104-2025_02_06-03_17_59.tar.zst"
file_name = "vzdump-lxc-104.tar.zst"
}
}
```
```
❯ tofu apply
+ create
+ resource "proxmox_virtual_environment_file" …
```
=> fix(file): fix for datastore does not support content type "dump"

docs/guides/cloud-init.md, templates/guides/cloud-init.md.tmpl
Fix incorrect argument name from `metadata_file_id` to `meta_data_file_id` in cloud-init docs.
=> fix(docs): update incorrect reference to meta_data_file_id

docs/data-sources/virtual_environment_container.md, example/data_source_virtual_environment_container.tf, proxmoxtf/datasource/container.go, proxmoxtf/datasource/container_test.go, proxmoxtf/datasource/vm.go, proxmoxtf/provider/datasources.go
```
$ cat datasource.tf 
data "proxmox_virtual_environment_container" "test" {
vm_id = "133"
node_name    = "pve-host"
}
output "ip_address" {
value = data.proxmox_virtual_environment_container.test
}
$ tofu apply
╷
│ Warning: Provider development overrides are in effect
│ 
│ The following provider development overrides are set in the CLI configuration:
│  - bpg/proxmox in /home/harm/go/bin
│ 
│ The behavior may therefore not match any released version of the provider and applying changes may cause the state to become incompatible with published releases.
╵
data.proxmox_virtual_environment_container.test: Reading...
data.proxmox_virtual_environment_container.test: Read complete after 0s [id=133]
Changes to Outputs:
+ ip_address = {
+ id        = "133"
+ name      = "k3s-controller-02"
+ …
```
=> feat(lxc): add container datasource

docs/resources/virtual_environment_container.md
List of tags unsorted do not impact `terraform plan` differences seen by terraform. But having tags with capital letters do.
Tested with Proxmox 8.3.5.
=> fix(docs): clarify `tags` behaviour for container

fwprovider/test/resource_container_test.go, proxmoxtf/resource/container/container.go
Previously, a configuration generated from an existing container looked like this:
```tf
resource "proxmox_virtual_environment_container" "testcontainer" {
...
timeout_update      = null
unprivileged        = null
vm_id               = null
...
```
This led to tofu wanting to replace the container based on the just generated config `unprivileged = null` (which results in false) and the difference to the imported state `unprivileged = null`. This is also an issue with `unprivileged = true|false`, as it's compared against null.
Now, the property `unprivileged` is imported correctly:
```tf
resource "proxmox_virtual_environment_container" "testcontainer" {
...
timeout_update      = null
unprivileged        = true
vm_id               = null
...
```
- Please vote on this pull request by adding …
=> fix(lxc): multiple issues during container import

docs/resources/virtual_environment_vm.md, example/resource_virtual_environment_vm.tf, fwprovider/test/resource_vm_test.go, proxmox/nodes/vms/custom_virtiofs_share.go, proxmox/nodes/vms/custom_virtiofs_share_test.go, proxmox/nodes/vms/vms_types.go, proxmox/nodes/vms/vms_types_test.go, proxmoxtf/resource/vm/validators.go, proxmoxtf/resource/vm/vm.go, proxmoxtf/resource/vm/vm_test.go
This adds virtiofs support for virtual machines.
Usage:
```hcl
resource "proxmox_virtual_environment_vm" "test_vm1" {
/* ... */
virtiofs {
dir_id = "test"
cache = "always"
direct_io = true
expose_acl = false
expose_xattr = false
}
}
```
Relates #1892 - directory mapping creation not yet implemented
Relates #1902 - acceptance test is commented out and …
=> feat(vm): add support for `virtiofs`

proxmoxtf/resource/container/container.go
Removed rebootRequired in containerUpdate function when changes are being applied to the cpu. Tested the build in my cluster and this fixes the bug reported in #1920
Closes [#1920](https://github.com/bpg/terraform-provider-proxmox/issues/1920)
=> fix(container): do not reboot for cpu block changes

docs/resources/virtual_environment_vm.md, proxmox/nodes/vms/custom_amdsev.go, proxmox/nodes/vms/vms_types.go, proxmoxtf/resource/vm/validators.go, proxmoxtf/resource/vm/vm.go
This pull request adds support for the `amd-sev` parameter to enable AMD SEV features on QEMU powered vms. Proxmox **8.4** adds support for AMD SEV-SNP. This was added onto the amd-sev parameter which already enabled SEV and SEV-ES. I have found no prior mention of amd-sev in this repository.
The `amd_sev` schema is defined with five parameters. The defaults match the defaults defined by Proxmox.
```
amd_sev {
type = "snp" # default "std" (sev only)
allow_smt = true # default true
kernel_hashes = true # default false
no_key_sharing = false # default false
no_debug = false # default false
}
```
more details are available in the docs.
`CustomAMDSEV` object is added to the provider to communicate with Proxmox. The pve api docs is somewhat unclear on the format of the outgoing object …
=> feat(vm): add support for amd-sev parameter

docs/resources/virtual_environment_download_file.md, fwprovider/nodes/resource_download_file.go, fwprovider/nodes/resource_download_file_test.go, fwprovider/test/resource_file_test.go
This is probably a proper fix for (at least those i could find):
- https://github.com/bpg/terraform-provider-proxmox/issues/1740
- https://github.com/bpg/terraform-provider-proxmox/issues/1440
- workaround added in https://github.com/bpg/terraform-provider-proxmox/pull/1940
In short, comparing "remote size" of file and replacing it on remote file changes, comes with a lot more problems then it solves. After taking some time on it, I could not find any reason why anybody could want to recreate VM after Content-Length header of some download iso or qcow2 or anything else has changed. I think opposite is maybe even true, nobody really wants that. It was introduced by me in https://github.com/bpg/terraform-provider-proxmox/pull/837 without deep thinking and I'm almost sure this is unwanted …
=> fix(file): properly handle overwrite option behavior in `proxmox_virtual_environment_download_file`

fwprovider/nodes/network/resource_linux_bridge.go, fwprovider/nodes/network/resource_linux_vlan.go
Reference to the resources proxmox_virtual_environment_network_linux_bridge + proxmox_virtual_environment_network_linux_vlan . 
I'm currently involved in a Crossplane provider development based on this provider of Proxmox that is the best by far out there (so, thanks for this honestly, incredible work for the Proxmox community :) ). 
Crossplane, uses on its backend this Terraform provider to interact with resources in the following way: 
- Init -> - apply -refresh-only -> (if there is any drift) -> apply   (all this done automatically) and using this Terraform code for its base.  (Crossplane keeps doing this continuous refresh constantly)
So the problem I've found it's that Terraform asssigns the ID before even the resource it's created on Proxmox, making the update() and read() cycle to …
=> fix(network): improve error handling on `create`/`read`/`update`

README.md, docs/guides/cloud-image.md, docs/guides/cloud-init.md, docs/index.md, docs/resources/virtual_environment_vm.md, example/resource_virtual_environment_vm.tf, examples/guides/cloud-image/centos-qcow2/main.tf, examples/guides/cloud-image/centos-qcow2/provider.tf, examples/guides/cloud-image/debian-from-storage/main.tf, examples/guides/cloud-image/ubuntu-img/main.tf, examples/guides/cloud-image/ubuntu-img/provider.tf, examples/guides/cloud-init/custom/main.tf, examples/guides/cloud-init/native/main.tf, examples/guides/cloud-init/native/provider.tf, fwprovider/test/resource_vm_disks_test.go, proxmox/nodes/vms/custom_storage_device.go, proxmoxtf/resource/vm/disk/disk.go, proxmoxtf/resource/vm/disk/schema.go, proxmoxtf/resource/vm/disk/schema_test.go, proxmoxtf/resource/vm/vm.go
Running an example from /examples/guides/cloud-image/ubuntu-img
```
+ create
+ resource "proxmox_virtual_environment_download_file" "ubuntu_cloud_image" {
+ content_type        = "import"
+ datastore_id        = "local"
+ file_name           = "jammy-server-cloudimg-amd64.qcow2"
+ id                  = (known after apply)
+ node_name           = "pve"
+ overwrite           = true
+ overwrite_unmanaged = false
+ size                = (known after apply)
+ upload_timeout      = 600
+ url                 = "https://cloud-images.ubuntu.com/jammy/current/jammy-server-cloudimg-amd64.img"
+ verify              = …
```
=> feat(vm): Import Disk via API.

docs/index.md, fwprovider/nodes/resource_download_file_test.go, fwprovider/provider.go, fwprovider/test/resource_file_test.go, proxmox/ssh/client.go, proxmoxtf/provider/provider.go, proxmoxtf/provider/schema.go
This PR adds support for ssh agent forwarding using the Go ssh agent forwarding std lib. I found that with `pam_ssh_agent_auth` the `try_sudo` check with `sudo -n`  would not work unless sudo was run once first (presumably starting a session). To work around this I added an additional check to see if sudo worked with out restriction with `sudo whoami` then falling back to the previous behavior if it failed. 
To properly test this the [pam_ssh_agetnt_auth](https://manpages.debian.org/testing/libpam-ssh-agent-auth/pam_ssh_agent_auth.8.en.html) would need to be set up on the PVE node. I have validated this works with my setup, and also validated there were no regressions with the existing documentation regarding the sudoers file. 
If there is an ideal way to add tests for this let me know, …
=> feat(provider): add support for ssh `agent_forwarding`
